const fs=require("fs"),path=require("path"),crypto=require("crypto"),Database=require("better-sqlite3");
const sha256=file=>crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
class BackupManager{constructor({db,databaseFile,backupDir}){this.db=db;this.databaseFile=path.resolve(databaseFile);this.backupDir=path.resolve(backupDir);}
async create({label="manual",retentionDays=30}={}){if(!this.db?.open)throw new Error("Open SQLite database is required");fs.mkdirSync(this.backupDir,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,"-");const safe=String(label).replace(/[^a-z0-9_-]/gi,"-").slice(0,40)||"manual",file=path.join(this.backupDir,`pharmacy-${stamp}-${safe}.sqlite3`);await this.db.backup(file);const integrity=this.inspect(file);if(integrity.quickCheck!=="ok")throw new Error("Backup integrity check failed");const manifest={version:1,createdAt:new Date().toISOString(),source:path.basename(this.databaseFile),file:path.basename(file),sha256:sha256(file),bytes:fs.statSync(file).size,schemaMigrations:integrity.schemaMigrations,quickCheck:integrity.quickCheck};fs.writeFileSync(`${file}.json`,JSON.stringify(manifest,null,2));this.prune(retentionDays);return{file,manifestFile:`${file}.json`,manifest};}
verify(file){const resolved=path.resolve(file);if(path.dirname(resolved)!==this.backupDir)throw new Error("Backup must be inside the configured backup directory");const manifestFile=`${resolved}.json`;if(!fs.existsSync(resolved)||!fs.existsSync(manifestFile))throw new Error("Backup or manifest was not found");const manifest=JSON.parse(fs.readFileSync(manifestFile,"utf8"));if(manifest.sha256!==sha256(resolved))throw new Error("Backup checksum mismatch");const integrity=this.inspect(resolved);if(integrity.quickCheck!=="ok")throw new Error("Backup integrity check failed");if(integrity.schemaMigrations!==manifest.schemaMigrations)throw new Error("Backup schema manifest mismatch");return{valid:true,file:resolved,manifest,integrity};}
restoreOffline({backupFile,targetFile,databaseClosed=false}){if(!databaseClosed)throw new Error("Database must be closed before restore");const verified=this.verify(backupFile),target=path.resolve(targetFile);if(target===verified.file)throw new Error("Backup and restore target must be different");fs.mkdirSync(path.dirname(target),{recursive:true});const safety=`${target}.pre-restore-${Date.now()}`;if(fs.existsSync(target))fs.copyFileSync(target,safety);const temp=`${target}.restore-${process.pid}-${Date.now()}`;try{fs.copyFileSync(verified.file,temp);if(this.inspect(temp).quickCheck!=="ok")throw new Error("Restored copy failed integrity check");fs.copyFileSync(temp,target);return{restored:true,target,safetyFile:fs.existsSync(safety)?safety:null,sha256:sha256(target)};}finally{if(fs.existsSync(temp))fs.rmSync(temp);}}
inspect(file){const check=new Database(file,{readonly:true,fileMustExist:true});try{return{quickCheck:check.pragma("quick_check",{simple:true}),schemaMigrations:Number(check.prepare("SELECT COUNT(*) count FROM SchemaMigrations").get().count)};}finally{check.close();}}
prune(days){const cutoff=Date.now()-Math.max(1,Number(days)||30)*86400000;for(const item of fs.readdirSync(this.backupDir)){if(!/^pharmacy-.*\.sqlite3(\.json)?$/.test(item))continue;const file=path.join(this.backupDir,item);if(fs.statSync(file).mtimeMs<cutoff)fs.rmSync(file);}}
}
module.exports={BackupManager,sha256};
