const {test,expect,_electron}=require('@playwright/test');const fs=require('fs'),path=require('path'),os=require('os');
test('P030 configure pack, calculate prices and sell configured default unit',async()=>{
 const env={...process.env,TECHORBIT_UI_DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'techorbit-packing-'))};delete env.ELECTRON_RUN_AS_NODE;delete env.TECHORBIT_UI_DATABASE;
 const app=await _electron.launch({executablePath:require('../../node_modules/electron'),args:[path.resolve(__dirname,'../desktop/main.cjs')],env});
 try{const page=await app.firstWindow();await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('TechOrbit-Demo-2026!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Products',exact:true}).click();await page.getByRole('button',{name:'Packing ORS sachet',exact:true}).click();
 await expect(page.getByText('This product has stock or history.',{exact:false})).toBeVisible();
 const existing=await page.getByRole('group').count();await page.getByRole('button',{name:'Add unit',exact:true}).click();const i=existing+1;
 await page.getByLabel('Unit name '+i,{exact:true}).fill('bulk pack');await page.getByLabel('Base quantity '+i,{exact:true}).fill('20');await page.getByLabel('Unit price '+i,{exact:true}).fill('900');await page.getByLabel('Default unit '+i,{exact:true}).check();await page.getByLabel('Price source unit',{exact:true}).selectOption(String(i-1));await page.getByRole('button',{name:'Calculate other prices',exact:true}).click();await page.getByRole('dialog').evaluate(el=>el.scrollTop=0);await expect.poll(()=>page.getByRole('dialog').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:path.resolve(__dirname,'../evidence/packing-light.png')});await page.getByRole('button',{name:'Save packing',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Packing ORS sachet',exact:true}).click();await expect(page.getByLabel('Unit price 1',{exact:true})).toHaveValue('4500');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Dark',exact:true}).click();await page.getByRole('button',{name:'Products',exact:true}).click();await page.getByRole('button',{name:'Packing ORS sachet',exact:true}).click();await expect(page.getByLabel('Unit price 1',{exact:true})).toHaveValue('4500');await page.screenshot({path:path.resolve(__dirname,'../evidence/packing-dark.png')});await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('button',{name:'Point of Sale',exact:true}).click();const search=page.getByLabel('Scan barcode or search medicine');await search.fill('0012345678903');await search.press('Enter');await expect(page.getByLabel('Unit line 1')).toHaveValue('bulk pack');await expect(page.getByLabel('Quantity line 1')).toHaveValue('1');await page.getByRole('button',{name:'Pay & Print',exact:false}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByText('bulk pack',{exact:false})).toBeVisible();
 }finally{await app.close()}
});
