const crypto=require("crypto"),fs=require("fs"),path=require("path"),bcrypt=require("bcrypt");const {hasPermission}=require("../sqlite/services/auth-bootstrap");
const b64=x=>Buffer.from(x).toString("base64url"),parse=x=>JSON.parse(Buffer.from(x,"base64url").toString("utf8"));
function loadOrCreateSecret(file){fs.mkdirSync(path.dirname(file),{recursive:true});if(fs.existsSync(file)){const value=fs.readFileSync(file,"utf8").trim();if(value.length<43)throw new Error("Session secret file is invalid");return value;}const value=crypto.randomBytes(48).toString("base64url");fs.writeFileSync(file,value,{encoding:"utf8",mode:0o600,flag:"wx"});return value;}
function signToken(payload,secret,{ttlSeconds=8*3600}={}){const body=b64(JSON.stringify({...payload,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+ttlSeconds})),sig=crypto.createHmac("sha256",secret).update(body).digest("base64url");return `${body}.${sig}`;}
function verifyToken(token,secret){const [body,sig]=String(token||"").split(".");if(!body||!sig)throw new Error("Invalid session token");const expected=crypto.createHmac("sha256",secret).update(body).digest(),actual=Buffer.from(sig,"base64url");if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))throw new Error("Invalid session token");const payload=parse(body);if(!payload.exp||payload.exp<Math.floor(Date.now()/1000))throw new Error("Session token expired");return payload;}
class SessionAuthService{constructor(db,secret){this.db=db;this.secret=secret;}login({username,password}){const user=this.db.prepare(`SELECT u.*,r.code role_code FROM Users u JOIN Roles r ON r.id=u.role_id WHERE u.username=? AND u.active=1`).get(String(username||"").trim());if(!user||!bcrypt.compareSync(String(password||""),user.password_hash))throw new Error("Invalid username or password");return{token:signToken({sub:user.id,role:user.role_code,mustChangePassword:Boolean(user.must_change_password)},this.secret),user:{id:user.id,username:user.username,displayName:user.display_name,roleCode:user.role_code,mustChangePassword:Boolean(user.must_change_password)}};}changePassword({userId,currentPassword,newPassword}){const user=this.db.prepare("SELECT * FROM Users WHERE id=? AND active=1").get(userId);if(!user||!bcrypt.compareSync(String(currentPassword||""),user.password_hash))throw new Error("Current password is incorrect");if(String(newPassword||"").length<12||!/[A-Z]/.test(newPassword)||!/[a-z]/.test(newPassword)||!/[0-9]/.test(newPassword)||!(/[^A-Za-z0-9]/.test(newPassword)))throw new Error("New password must be 12+ characters with upper, lower, number and symbol");this.db.prepare("UPDATE Users SET password_hash=?,must_change_password=0,updated_at=? WHERE id=?").run(bcrypt.hashSync(newPassword,12),new Date().toISOString(),user.id);return{changed:true};}}
function createAuthMiddleware({db,secret,required=false}){return(req,res,next)=>{if(!required)return next();try{const header=req.get("authorization")||"";const payload=verifyToken(header.startsWith("Bearer ")?header.slice(7):"",secret);const user=db().prepare("SELECT active,must_change_password FROM Users WHERE id=?").get(payload.sub);if(!user?.active)throw new Error("User is inactive");if(user.must_change_password&&!req.path.endsWith("/change-password"))return res.status(403).json({error:"PASSWORD_CHANGE_REQUIRED"});req.auth=payload;next();}catch(e){res.status(401).json({error:"AUTH_REQUIRED",message:e.message});}};}
function requirePermission(db,code){return(req,res,next)=>{if(!req.auth||!hasPermission(db(),req.auth.sub,code))return res.status(403).json({error:"PERMISSION_DENIED",permission:code});next();};}
module.exports={loadOrCreateSecret,signToken,verifyToken,SessionAuthService,createAuthMiddleware,requirePermission};
