class CashClosingService{constructor(db){this.db=db;this.openTx=db.transaction(x=>this.openInternal(x));this.closeTx=db.transaction(x=>this.closeInternal(x));}
open(x){const opening=Number(x?.openingCashMinor);if(!x?.deviceId?.trim()||!Number.isInteger(opening)||opening<0)throw new Error("Device and non-negative opening cash are required");return this.openTx(x);}
openInternal(x){const at=x.openedAt||new Date().toISOString(),now=new Date().toISOString();const id=this.db.prepare("INSERT INTO CashShifts(user_id,device_id,opened_at,opening_cash_minor,status,created_at) VALUES (?,?,?,?,'open',?)").run(x.userId||null,x.deviceId.trim(),at,x.openingCashMinor,now).lastInsertRowid;this.audit("cash_shift.open",id,x,{openingCashMinor:x.openingCashMinor});return this.db.prepare("SELECT * FROM CashShifts WHERE id=?").get(id);}
close(x){if(!x?.shiftId||!Number.isInteger(Number(x.countedCashMinor))||Number(x.countedCashMinor)<0)throw new Error("Shift and non-negative counted cash are required");return this.closeTx(x);}
closeInternal(x){const shift=this.db.prepare("SELECT * FROM CashShifts WHERE id=?").get(x.shiftId);if(!shift)throw new Error("Cash shift was not found");if(shift.status!=="open")throw new Error("Cash shift is already closed");const at=x.closedAt||new Date().toISOString();const cash=this.db.prepare(`SELECT COALESCE(SUM(CASE direction WHEN 'in' THEN amount_minor ELSE -amount_minor END),0) net FROM MoneyMovements WHERE method='cash' AND occurred_at>=? AND occurred_at<=?`).get(shift.opened_at,at).net;const expected=Number(shift.opening_cash_minor)+Number(cash),counted=Number(x.countedCashMinor),variance=counted-expected;this.db.prepare("UPDATE CashShifts SET status='closed',closed_at=?,expected_cash_minor=?,counted_cash_minor=?,variance_minor=?,notes=? WHERE id=?").run(at,expected,counted,variance,x.notes||null,shift.id);this.audit("cash_shift.close",shift.id,x,{expected,counted,variance});return{shiftId:Number(shift.id),expectedCashMinor:expected,countedCashMinor:counted,varianceMinor:variance,status:"closed"};}
sixMonthReport(asOf=new Date().toISOString()){const end=new Date(asOf);if(Number.isNaN(end.getTime()))throw new Error("Invalid report date");const months=[];for(let offset=5;offset>=0;offset--){const start=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-offset,1));const next=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,1));const from=start.toISOString(),to=next.toISOString();const sales=this.db.prepare("SELECT COALESCE(SUM(final_total_minor),0) total,COALESCE(SUM(cogs_minor),0) cogs FROM Sales WHERE status='posted' AND sold_at>=? AND sold_at<?").get(from,to);const expenses=this.db.prepare("SELECT COALESCE(SUM(amount_minor),0) total FROM Expenses WHERE status='posted' AND expense_date>=? AND expense_date<?").get(from,to).total;const purchases=this.db.prepare("SELECT COALESCE(SUM(total_minor),0) total FROM Purchases WHERE status='posted' AND purchased_at>=? AND purchased_at<?").get(from,to).total;const returns=this.db.prepare("SELECT COALESCE(SUM(total_minor),0) total FROM PurchaseReturns WHERE returned_at>=? AND returned_at<?").get(from,to).total;months.push({month:from.slice(0,7),salesMinor:Number(sales.total),cogsMinor:Number(sales.cogs),grossProfitMinor:Number(sales.total)-Number(sales.cogs),expensesMinor:Number(expenses),purchasesMinor:Number(purchases),purchaseReturnsMinor:Number(returns)});}return{periodStart:`${months[0].month}-01`,periodEnd:end.toISOString().slice(0,10),months,totals:months.reduce((a,m)=>{for(const k of ["salesMinor","cogsMinor","grossProfitMinor","expensesMinor","purchasesMinor","purchaseReturnsMinor"])a[k]+=m[k];return a;},{salesMinor:0,cogsMinor:0,grossProfitMinor:0,expensesMinor:0,purchasesMinor:0,purchaseReturnsMinor:0})};}
closeSixMonth(x){const report=this.sixMonthReport(x.asOf);const now=new Date().toISOString();const id=this.db.prepare("INSERT INTO PeriodClosings(period_type,period_start,period_end,totals_json,closed_at,closed_by,notes) VALUES ('six_month',?,?,?,?,?,?)").run(report.periodStart,report.periodEnd,JSON.stringify(report.totals),now,x.closedBy||null,x.notes||null).lastInsertRowid;this.audit("period.close",id,x,report);return{closingId:Number(id),...report};}
audit(action,id,x,next){this.db.prepare(`INSERT INTO AuditLog(occurred_at,user_id,action,entity_type,entity_id,new_json,reason,device_id) VALUES (?,?,?,'closing',?,?,?,?)`).run(new Date().toISOString(),x.userId||x.closedBy||null,action,String(id),JSON.stringify(next),x.reason||null,x.deviceId||null);}}
module.exports={CashClosingService};
