const METHODS=new Set(["cash","card","bank_transfer","mobile_wallet","other"]);
class ExpensesService{constructor(db){this.db=db;this.postTx=db.transaction(x=>this.postInternal(x));this.voidTx=db.transaction(x=>this.voidInternal(x));}
post(x){if(!x?.idempotencyKey?.trim())throw new Error("Idempotency key is required");const old=this.db.prepare("SELECT * FROM Expenses WHERE idempotency_key=?").get(x.idempotencyKey.trim());if(old)return{...this.result(old),idempotent:true};return this.postTx(x);}
postInternal(x){const category=this.db.prepare("SELECT id FROM ExpenseCategories WHERE id=? AND active=1").get(x.categoryId);if(!category)throw new Error("Active expense category was not found");const amount=Number(x.amountMinor),method=x.method||"cash";if(!Number.isInteger(amount)||amount<=0)throw new Error("Expense amount must be a positive integer");if(!METHODS.has(method))throw new Error("Unsupported payment method");if(!x.description?.trim())throw new Error("Expense description is required");const at=x.expenseDate||new Date().toISOString(),now=new Date().toISOString();const id=this.db.prepare(`INSERT INTO Expenses(category_id,amount_minor,method,expense_date,vendor,description,idempotency_key,status,created_by,created_at) VALUES (?,?,?,?,?,?,?,'posted',?,?)`).run(category.id,amount,method,at,x.vendor||null,x.description.trim(),x.idempotencyKey.trim(),x.createdBy||null,now).lastInsertRowid;this.db.prepare(`INSERT INTO MoneyMovements(direction,method,amount_minor,reference_type,reference_id,occurred_at,user_id,note) VALUES ('out',?,?,'expense',?,?,?,?)`).run(method,amount,String(id),at,x.createdBy||null,x.description.trim());this.audit("expense.post",id,x,null,{amountMinor:amount,method});return{...this.result(this.db.prepare("SELECT * FROM Expenses WHERE id=?").get(id)),idempotent:false};}
void(x){if(!x?.expenseId||!x.reason?.trim())throw new Error("Expense ID and void reason are required");return this.voidTx(x);}
voidInternal(x){const row=this.db.prepare("SELECT * FROM Expenses WHERE id=?").get(x.expenseId);if(!row)throw new Error("Expense was not found");if(row.status!=="posted")throw new Error("Expense is already void");const now=new Date().toISOString();this.db.prepare("UPDATE Expenses SET status='void',voided_at=?,voided_by=?,void_reason=? WHERE id=?").run(now,x.createdBy||null,x.reason.trim(),row.id);this.db.prepare(`INSERT INTO MoneyMovements(direction,method,amount_minor,reference_type,reference_id,occurred_at,user_id,note) VALUES ('in',?,?,'expense_void',?,?,?,?)`).run(row.method,row.amount_minor,String(row.id),now,x.createdBy||null,x.reason.trim());this.audit("expense.void",row.id,x,{status:"posted"},{status:"void"});return this.result(this.db.prepare("SELECT * FROM Expenses WHERE id=?").get(row.id));}
audit(action,id,x,previous,next){this.db.prepare(`INSERT INTO AuditLog(occurred_at,user_id,action,entity_type,entity_id,previous_json,new_json,reason) VALUES (?,?,?,'expense',?,?,?,?)`).run(new Date().toISOString(),x.createdBy||null,action,String(id),previous&&JSON.stringify(previous),JSON.stringify(next),x.reason||null);}
result(row){return{expenseId:Number(row.id),amountMinor:Number(row.amount_minor),status:row.status};}}
module.exports={ExpensesService};
