const crypto=require("crypto");
const PRODUCT_TYPES=new Set(["medicine","general","cosmetic"]);const TAX=new Set(["taxable","exempt"]);
const bool=value=>[true,1,"1","yes","y","true"].includes(typeof value==="string"?value.trim().toLowerCase():value);
const text=value=>value==null||String(value).trim()===""?null:String(value).trim();
const number=(value,name,errors,{min=0}={})=>{const parsed=Number(value??0);if(!Number.isFinite(parsed)||parsed<min){errors.push(`${name} must be a number not less than ${min}`);return 0;}return parsed;};
const money=(value,name,errors)=>Math.round(number(value,name,errors)*100);
function normalizeProduct(raw){const errors=[];const taxStatus=(text(raw.tax_status)||"exempt").toLowerCase();const productType=(text(raw.product_type)||"medicine").toLowerCase();const name=text(raw.name);if(!name)errors.push("name is required");if(!TAX.has(taxStatus))errors.push("tax_status must be taxable or exempt");if(!PRODUCT_TYPES.has(productType))errors.push("product_type must be medicine, general or cosmetic");const gst=number(raw.gst_percent,"gst_percent",errors,{min:0});if(gst>100)errors.push("gst_percent cannot exceed 100");const baseUnit=(text(raw.base_unit)||"piece").toLowerCase();const normalized={sku:text(raw.sku),barcode:text(raw.barcode),name,genericName:text(raw.generic_name),manufacturer:text(raw.manufacturer),category:text(raw.category),productType,dosageForm:text(raw.dosage_form),strength:text(raw.strength),packDescription:text(raw.pack_description),baseUnit,defaultSalePriceMinor:money(raw.base_sale_price,"base_sale_price",errors),stripSalePriceMinor:text(raw.strip_sale_price)==null?null:money(raw.strip_sale_price,"strip_sale_price",errors),boxSalePriceMinor:text(raw.box_sale_price)==null?null:money(raw.box_sale_price,"box_sale_price",errors),minimumStock:number(raw.minimum_stock,"minimum_stock",errors),reorderLevel:number(raw.reorder_level,"reorder_level",errors),prescriptionRequired:bool(raw.prescription_required),controlledMedicine:bool(raw.controlled_medicine),taxStatus,gstRateBasisPoints:taxStatus==="exempt"?0:Math.round(gst*100),active:raw.active==null||text(raw.active)==null?true:bool(raw.active),notes:text(raw.notes),unitsPerStrip:number(raw.units_per_strip||1,"units_per_strip",errors,{min:1}),stripsPerBox:number(raw.strips_per_box||1,"strips_per_box",errors,{min:1})};return{normalized,errors};}
class ProductImportService{
 constructor(db){this.db=db;}
 preview({rows,sourceName="products.xlsx",sourceBuffer,duplicatePolicy="error",createdBy=null}){if(!Array.isArray(rows)||rows.length===0)throw new Error("Import file has no product rows");if(!["error","skip","update"].includes(duplicatePolicy))throw new Error("Invalid duplicate policy");const sha=crypto.createHash("sha256").update(sourceBuffer||JSON.stringify(rows)).digest("hex");const now=new Date().toISOString();return this.db.transaction(()=>{const jobId=Number(this.db.prepare(`INSERT INTO ImportJobs(import_type,source_name,source_sha256,duplicate_policy,status,created_by,created_at) VALUES ('product_master',?,?,?,'previewed',?,?)`).run(sourceName,sha,duplicatePolicy,createdBy,now).lastInsertRowid);const insert=this.db.prepare(`INSERT INTO ImportRows(import_job_id,row_number,raw_json,normalized_json,action,errors_json) VALUES (?,?,?,?,?,?)`);const seenBarcodes=new Set(),seenSkus=new Set();let valid=0,error=0,skipped=0;const preview=[];rows.forEach((raw,index)=>{const rowNumber=index+2;const {normalized,errors}=normalizeProduct(raw);if(normalized.barcode&&seenBarcodes.has(normalized.barcode))errors.push("duplicate barcode within import file");if(normalized.sku&&seenSkus.has(normalized.sku))errors.push("duplicate SKU within import file");if(normalized.barcode)seenBarcodes.add(normalized.barcode);if(normalized.sku)seenSkus.add(normalized.sku);const existing=normalized.barcode?this.db.prepare("SELECT id FROM Products WHERE barcode=?").get(normalized.barcode):normalized.sku?this.db.prepare("SELECT id FROM Products WHERE sku=?").get(normalized.sku):null;let action="insert";if(existing){if(duplicatePolicy==="error")errors.push("product barcode or SKU already exists");else action=duplicatePolicy==="skip"?"skip":"update";}if(errors.length)action="error";if(action==="error")error++;else if(action==="skip")skipped++;else valid++;insert.run(jobId,rowNumber,JSON.stringify(raw),JSON.stringify(normalized),action,JSON.stringify(errors));preview.push({rowNumber,action,errors,normalized});});this.db.prepare("UPDATE ImportJobs SET total_rows=?,valid_rows=?,error_rows=?,skipped_rows=? WHERE id=?").run(rows.length,valid,error,skipped,jobId);return{jobId,sha256:sha,totalRows:rows.length,validRows:valid,errorRows:error,skippedRows:skipped,rows:preview};})();}
 commit(jobId){return this.db.transaction(()=>{const job=this.db.prepare("SELECT * FROM ImportJobs WHERE id=?").get(jobId);if(!job)throw new Error("Import job was not found");if(job.status!=="previewed")throw new Error("Import job is not available for commit");if(job.error_rows>0)throw new Error("Import has validation errors and cannot be committed");if(this.db.prepare("SELECT id FROM ImportJobs WHERE import_type=? AND source_sha256=? AND status='committed' AND id<>?").get(job.import_type,job.source_sha256,job.id))throw new Error("This file was already committed");const rows=this.db.prepare("SELECT * FROM ImportRows WHERE import_job_id=? AND action IN ('insert','update') ORDER BY row_number").all(jobId);let committed=0;for(const row of rows){const p=JSON.parse(row.normalized_json);p.createdBy=job.created_by;let product;if(row.action==="insert"){product=this.insertProduct(p);}else{product=this.updateProduct(p);}this.configureUnits(product.id,p);this.db.prepare("UPDATE ImportRows SET product_id=? WHERE id=?").run(product.id,row.id);committed++;}const now=new Date().toISOString();this.db.prepare("UPDATE ImportJobs SET status='committed',committed_rows=?,committed_at=? WHERE id=?").run(committed,now,jobId);this.db.prepare(`INSERT INTO AuditLog(occurred_at,user_id,action,entity_type,entity_id,new_json) VALUES (?,?,'product.import','import_job',?,?)`).run(now,job.created_by,String(jobId),JSON.stringify({sourceName:job.source_name,sha256:job.source_sha256,committed,skipped:job.skipped_rows}));this.db.pragma("optimize");return{jobId,status:"committed",committedRows:committed,skippedRows:job.skipped_rows};})();}
 insertProduct(p){const {ProductsRepository}=require("../repositories/products");return new ProductsRepository(this.db).create(p);}
 updateProduct(p){const current=p.barcode?this.db.prepare("SELECT id FROM Products WHERE barcode=?").get(p.barcode):this.db.prepare("SELECT id FROM Products WHERE sku=?").get(p.sku);if(!current)throw new Error("Product selected for update no longer exists");const now=new Date().toISOString();this.db.prepare(`UPDATE Products SET sku=?,barcode=?,name=?,generic_name=?,manufacturer=?,category=?,product_type=?,dosage_form=?,strength=?,pack_description=?,base_unit=?,default_sale_price_minor=?,box_sale_price_minor=?,strip_sale_price_minor=?,minimum_stock=?,reorder_level=?,prescription_required=?,controlled_medicine=?,gst_rate_basis_points=?,tax_status=?,active=?,notes=?,updated_by=?,updated_at=? WHERE id=?`).run(p.sku,p.barcode,p.name,p.genericName,p.manufacturer,p.category,p.productType,p.dosageForm,p.strength,p.packDescription,p.baseUnit,p.defaultSalePriceMinor,p.boxSalePriceMinor,p.stripSalePriceMinor,p.minimumStock,p.reorderLevel,p.prescriptionRequired?1:0,p.controlledMedicine?1:0,p.gstRateBasisPoints,p.taxStatus,p.active?1:0,p.notes,p.createdBy,now,current.id);return{id:current.id};}
 configureUnits(productId,p){const units=[{unitName:p.baseUnit,baseQuantity:1,sellingPriceMinor:p.defaultSalePriceMinor,isDefaultSaleUnit:!p.stripSalePriceMinor&&!p.boxSalePriceMinor}];if(p.stripSalePriceMinor!=null)units.push({unitName:"strip",baseQuantity:p.unitsPerStrip,sellingPriceMinor:p.stripSalePriceMinor,isDefaultSaleUnit:!p.boxSalePriceMinor});if(p.boxSalePriceMinor!=null)units.push({unitName:"box",baseQuantity:p.unitsPerStrip*p.stripsPerBox,sellingPriceMinor:p.boxSalePriceMinor,isDefaultSaleUnit:true});const unique=[...new Map(units.map(u=>[u.unitName,u])).values()];if(unique.filter(u=>u.isDefaultSaleUnit).length!==1){unique.forEach(u=>u.isDefaultSaleUnit=false);unique[0].isDefaultSaleUnit=true;}const {ProductUnitsRepository}=require("../repositories/product-units");new ProductUnitsRepository(this.db).configure(productId,unique);}
}
module.exports={ProductImportService,normalizeProduct};
