const {SalesQuotationService}=require('./sales-quotation');
const DEFAULT_RECEIPT_PROFILE={pharmacyName:"TechOrbit Pharmacy POS",address:null,phone:null,taxRegistration:null,footer:"Thank you for your purchase"};

class SalesPostingService {
  constructor(db) { this.db=db;this.quotation=new SalesQuotationService(db);this.postTransaction=db.transaction((sale)=>this.postInternal(sale)); }
  post(sale) {return this.postTransaction(sale);}
  postInternal(sale) {
    const plan=this.quotation.plan(sale);
    const {soldAt,method,items,grossMinor,lineDiscountMinor,invoiceDiscountMinor,taxableMinor,gstMinor,exactTotalMinor,finalTotalMinor,cashTenderedMinor,cashChangeMinor,amountPaidMinor,balanceDueMinor,collectionMethod,customer,warnings}=plan;
    const now=new Date().toISOString();
    const saleResult=this.db.prepare(`INSERT INTO Sales
      (invoice_number,idempotency_key,sold_at,customer_id,customer_name_snapshot,customer_phone_snapshot,payment_method,payment_status,
       gross_minor,line_discount_minor,invoice_discount_minor,taxable_minor,gst_minor,exact_total_minor,rounding_minor,final_total_minor,
       amount_paid_minor,balance_due_minor,due_date,cogs_minor,status,created_by,created_at,request_fingerprint,cash_tendered_minor,cash_change_minor)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,'posted',?,?,?,?,?)`).run(sale.invoiceNumber.trim(),sale.idempotencyKey.trim(),soldAt,
      sale.customerId||null,customer?.name||null,customer?.phone||null,method,plan.paymentStatus,
      grossMinor,lineDiscountMinor,invoiceDiscountMinor,taxableMinor,gstMinor,exactTotalMinor,finalTotalMinor-exactTotalMinor,finalTotalMinor,
      amountPaidMinor,balanceDueMinor,sale.dueDate||null,sale.createdBy||null,now,sale.requestFingerprint||null,cashTenderedMinor,cashChangeMinor);
    const saleId=Number(saleResult.lastInsertRowid);let totalCogs=0;const postedItems=[];
    for(const item of items){const allocation=item.allocations,cogsMinor=item.cogsMinor;totalCogs+=cogsMinor;const itemWarnings=item.warnings;
      const itemResult=this.db.prepare(`INSERT INTO SaleItems
        (sale_id,line_number,product_id,product_name_snapshot,generic_name_snapshot,sale_unit,entered_quantity,base_quantity,
         original_unit_price_minor,charged_unit_price_minor,gross_minor,line_discount_type,line_discount_value,line_discount_minor,
         allocated_invoice_discount_minor,taxable_minor,gst_rate_basis_points,gst_minor,line_total_minor,cogs_minor,prescription_warning,controlled_warning,near_expiry_warning)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(saleId,item.lineNumber,item.product.id,item.product.name,item.product.generic_name,
        item.saleUnit,item.enteredQuantity,item.baseQuantity,item.originalUnitPriceMinor,item.chargedUnitPriceMinor,item.grossMinor,
        item.lineDiscountType||null,item.lineDiscountValue||0,item.lineDiscountMinor,item.invoiceDiscountMinor,item.taxableMinor,
        item.product.gst_rate_basis_points,item.gstMinor,item.lineTotalMinor,cogsMinor,item.product.prescription_required,item.product.controlled_medicine,itemWarnings.some(w=>w.type==='near_expiry')?1:0);
      const saleItemId=Number(itemResult.lastInsertRowid);
      for(const a of allocation){ const changed=this.db.prepare("UPDATE ProductBatches SET quantity_on_hand=quantity_on_hand-?,updated_at=? WHERE id=? AND quantity_on_hand>=?").run(a.quantity,now,a.batch.id,a.quantity);if(changed.changes!==1)throw new Error('Sellable stock changed before the sale could be posted. Review and retry.');
        this.db.prepare(`INSERT INTO SaleItemAllocations(sale_item_id,batch_id,base_quantity,expiry_date_snapshot,unit_cost_minor_snapshot,cogs_minor) VALUES (?,?,?,?,?,?)`).run(saleItemId,a.batch.id,a.quantity,a.batch.expiry_date,a.batch.unit_cost_minor,a.cogsMinor);
        this.db.prepare(`INSERT INTO InventoryMovements(product_id,batch_id,movement_type,quantity_delta,reference_type,reference_id,occurred_at,user_id,note) VALUES (?,?,'sale',?,'sale',?,?,?,?)`).run(item.product.id,a.batch.id,-a.quantity,String(saleId),soldAt,sale.createdBy||null,item.overrideBatchId?`Manual FEFO override: ${item.overrideReason}`:'FEFO allocation'); }
      postedItems.push({saleItemId,lineNumber:item.lineNumber,productId:item.product.id,baseQuantity:item.baseQuantity,originalUnitPriceMinor:item.originalUnitPriceMinor,chargedUnitPriceMinor:item.chargedUnitPriceMinor,grossMinor:item.grossMinor,lineDiscountMinor:item.lineDiscountMinor,gstMinor:item.gstMinor,lineTotalMinor:item.lineTotalMinor,cogsMinor,allocations:allocation.map(a=>({batchId:a.batch.id,quantity:a.quantity})),warnings:itemWarnings}); }
    if(warnings.length&&sale.enforceWarningAcknowledgement&&!sale.warningAcknowledged)throw new Error('Acknowledge all medicine and expiry warnings before posting the sale');
    if(warnings.length&&sale.warningAcknowledged){if(!sale.createdBy)throw new Error('Acknowledging user is required');this.db.prepare(`INSERT INTO SaleWarningAcknowledgements(sale_id,warnings_json,doctor_name,prescription_reference,acknowledged_by,acknowledged_at) VALUES (?,?,?,?,?,?)`).run(saleId,JSON.stringify(warnings),sale.doctorName||null,sale.prescriptionReference||null,sale.createdBy,now);}
    this.db.prepare("UPDATE Sales SET cogs_minor=? WHERE id=?").run(totalCogs,saleId);
    if(amountPaidMinor>0) require('./money-movement').recordMoneyMovement(this.db,{direction:'in',method:collectionMethod,amountMinor:amountPaidMinor,referenceType:'sale',referenceId:saleId,occurredAt:soldAt,userId:sale.createdBy,deviceId:sale.deviceId,note:'Sale collection'});
    if(balanceDueMinor>0) this.db.prepare(`INSERT INTO Receivables(customer_id,source_type,source_id,original_minor,balance_minor,due_date,status,created_at,updated_at) VALUES (?,'sale',?,?,?,?,?,?,?)`).run(sale.customerId,String(saleId),balanceDueMinor,balanceDueMinor,sale.dueDate,amountPaidMinor>0?"partial":"unpaid",now,now);
    const profile=this.receiptProfile(),cashier=this.db.prepare(`SELECT u.id,u.display_name name,r.code roleCode FROM Users u JOIN Roles r ON r.id=u.role_id WHERE u.id=?`).get(sale.createdBy)||{id:sale.createdBy||null,name:'Unknown cashier',roleCode:sale.roleCode||'unknown'};
    const warningAcknowledgement=warnings.length&&sale.warningAcknowledged?{warnings,doctorName:sale.doctorName||null,prescriptionReference:sale.prescriptionReference||null,acknowledgedBy:cashier.name,acknowledgedAt:now}:null;
    const receiptSnapshot={version:1,profile,cashier,saleId,invoiceNumber:sale.invoiceNumber.trim(),soldAt,customer:{name:customer?.name||null,phone:customer?.phone||null},payment:{method,status:balanceDueMinor===0?'paid':amountPaidMinor>0?'partial':'credit',amountPaidMinor,balanceDueMinor,dueDate:sale.dueDate||null,cashTenderedMinor,cashChangeMinor},totals:{grossMinor,lineDiscountMinor,invoiceDiscountMinor,taxableMinor,gstMinor,exactTotalMinor,roundingMinor:finalTotalMinor-exactTotalMinor,finalTotalMinor},items:items.map(item=>({lineNumber:item.lineNumber,productName:item.product.name,genericName:item.product.generic_name,saleUnit:item.saleUnit,quantity:item.enteredQuantity,originalUnitPriceMinor:item.originalUnitPriceMinor,unitPriceMinor:item.chargedUnitPriceMinor,grossMinor:item.grossMinor,lineDiscountMinor:item.lineDiscountMinor,invoiceDiscountMinor:item.invoiceDiscountMinor,gstRateBasisPoints:item.product.gst_rate_basis_points,gstMinor:item.gstMinor,lineTotalMinor:item.lineTotalMinor})),warningAcknowledgement};
    this.db.prepare('INSERT INTO SaleReceiptSnapshots(sale_id,payload_json,created_at) VALUES(?,?,?)').run(saleId,JSON.stringify(receiptSnapshot),now);
    this.db.prepare(`INSERT INTO AuditLog(occurred_at,user_id,role_code,action,entity_type,entity_id,new_json,device_id) VALUES (?,?,?,'sale.post','sale',?,?,?)`).run(now,sale.createdBy||null,sale.roleCode||null,String(saleId),JSON.stringify({invoiceNumber:sale.invoiceNumber,finalTotalMinor,amountPaidMinor,balanceDueMinor,cashTenderedMinor,cashChangeMinor,totalCogs,invoiceDiscountType:sale.invoiceDiscountType||null,invoiceDiscountValue:sale.invoiceDiscountValue||0,invoiceDiscountMinor,pricing:items.map(item=>({lineNumber:item.lineNumber,productId:item.product.id,originalUnitPriceMinor:item.originalUnitPriceMinor,chargedUnitPriceMinor:item.chargedUnitPriceMinor,lineDiscountType:item.lineDiscountType||null,lineDiscountValue:item.lineDiscountValue||0,lineDiscountMinor:item.lineDiscountMinor})),batchOverrides:items.filter(item=>item.overrideBatchId).map(item=>({lineNumber:item.lineNumber,productId:item.product.id,suggestedBatchId:item.suggestedBatchId,selectedBatchId:item.overrideBatchId,reason:item.overrideReason,allocations:postedItems.find(posted=>posted.lineNumber===item.lineNumber)?.allocations||[]})),warningAcknowledgement:warnings.length?{warnings,acknowledged:Boolean(sale.warningAcknowledged),acknowledgedBy:sale.warningAcknowledged?sale.createdBy:null,acknowledgedAt:sale.warningAcknowledged?now:null,doctorName:sale.doctorName||null,prescriptionReference:sale.prescriptionReference||null}:null}),sale.deviceId||null);
    return {saleId,invoiceNumber:sale.invoiceNumber,grossMinor,lineDiscountMinor,invoiceDiscountMinor,taxableMinor,gstMinor,exactTotalMinor,roundingMinor:finalTotalMinor-exactTotalMinor,finalTotalMinor,amountPaidMinor,balanceDueMinor,cashTenderedMinor,cashChangeMinor,cogsMinor:totalCogs,items:postedItems,warnings};
  }
  receiptProfile(){const row=this.db.prepare("SELECT value_json FROM Settings WHERE key='receiptProfile'").get();if(!row)return DEFAULT_RECEIPT_PROFILE;try{const value=JSON.parse(row.value_json);return{pharmacyName:String(value.pharmacyName||DEFAULT_RECEIPT_PROFILE.pharmacyName),address:value.address?String(value.address):null,phone:value.phone?String(value.phone):null,taxRegistration:value.taxRegistration?String(value.taxRegistration):null,footer:String(value.footer||DEFAULT_RECEIPT_PROFILE.footer)}}catch{return DEFAULT_RECEIPT_PROFILE;}}
}
module.exports={SalesPostingService};
