const fs=require("fs"),os=require("os"),path=require("path");const {openDatabase}=require("../infrastructure/sqlite/database");const {ExpensesService}=require("../infrastructure/sqlite/services/expenses");describe("expenses ledger",()=>{let dir,db,category;beforeEach(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),"to-expense-"));db=openDatabase({filename:path.join(dir,"db.sqlite3")});category=db.prepare("SELECT id FROM ExpenseCategories WHERE name='Rent'").get();});afterEach(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});test("posts idempotent expense and controlled reversal",()=>{const s=new ExpensesService(db),input={categoryId:category.id,amountMinor:250000,method:"bank_transfer",description:"September rent",idempotencyKey:"rent-sep"};let x=s.post(input);expect(x).toMatchObject({status:"posted",idempotent:false});expect(s.post(input).idempotent).toBe(true);expect(()=>s.post({...input,description:"changed"})).toThrow(/different details/);x=s.void({expenseId:x.expenseId,reason:"Wrong account"});expect(x.status).toBe("void");expect(db.prepare("SELECT direction,amount_minor FROM MoneyMovements ORDER BY id").all()).toEqual([{direction:"out",amount_minor:250000},{direction:"in",amount_minor:250000}]);expect(db.prepare("SELECT COUNT(*) count FROM AuditLog WHERE entity_type='expense'").get().count).toBe(2);expect(()=>s.void({expenseId:x.expenseId,reason:"Again"})).toThrow(/already void/);});test("creates and settles one vendor payable without repeating expense recognition",()=>{const now="2026-09-20T12:00:00+05:00",vendor=Number(db.prepare("INSERT INTO Vendors(name,created_at,updated_at) VALUES('Landlord',?,?)").run(now,now).lastInsertRowid),s=new ExpensesService(db);const expense=s.post({categoryId:category.id,vendorId:vendor,incurredAmountMinor:100000,amountPaidMinor:25000,method:"cash",expenseDate:now,dueDate:"2026-10-01",reference:"RENT-01",description:"October rent",idempotencyKey:"expense-1"});expect(expense).toMatchObject({amountPaidMinor:25000,balanceDueMinor:75000});const payable=db.prepare("SELECT * FROM ExpensePayables").get(),payment={payableId:payable.id,amountMinor:75000,method:"bank_transfer",paidAt:"2026-09-21T12:00:00+05:00",reference:"BANK-1",idempotencyKey:"vendor-pay-1"};expect(s.settle(payment)).toMatchObject({balanceMinor:0,status:"paid",idempotent:false});expect(s.settle(payment).idempotent).toBe(true);expect(()=>s.settle({...payment,amountMinor:1})).toThrow(/different details/);expect(db.prepare("SELECT COUNT(*) count FROM Expenses").get().count).toBe(1);expect(db.prepare("SELECT SUM(amount_minor) total FROM MoneyMovements WHERE direction='out'").get().total).toBe(100000);});test('R026 vendor report reconciles partial payment, excludes initial paid portion and persists',async()=>{
 const report=require('../modernization/desktop/account-balance-reports.cjs'),now='2026-09-20T12:00:00+05:00';
 const vendor=Number(db.prepare("INSERT INTO Vendors(name,created_at,updated_at) VALUES('Landlord',?,?)").run(now,now).lastInsertRowid),s=new ExpensesService(db);
 s.post({categoryId:category.id,vendorId:vendor,incurredAmountMinor:100000,amountPaidMinor:25000,method:'cash',expenseDate:now,dueDate:'2026-10-01',reference:'R026-RENT',description:'Rent',idempotencyKey:'r026-expense'});
 const payable=db.prepare('SELECT id FROM ExpensePayables').get();s.settle({payableId:payable.id,amountMinor:30000,method:'bank_transfer',paidAt:now,idempotencyKey:'r026-pay'});
 const options={type:'vendor',now:new Date('2026-10-02T00:00:00Z')};
 expect(report.accountBalanceSummary(db,{party:'Landlord'},options).totals).toMatchObject({originalMinor:75000,paymentsMinor:30000,creditMinor:0,balanceMinor:45000,overdueMinor:45000});
 expect(report.accountBalanceSummary(db,{reference:'missing'},options).items).toHaveLength(0);
 expect(report.accountBalanceCsv(db,{},options).csv).toContain('"Total balance minor","45000"');
 expect(Buffer.from((await report.accountBalanceXlsx(db,{},options)).base64,'base64').subarray(0,2).toString()).toBe('PK');
 expect(Buffer.from(report.accountBalancePdf(db,{},options).base64,'base64').subarray(0,4).toString()).toBe('%PDF');
 db.close();db=openDatabase({filename:path.join(dir,'db.sqlite3')});expect(report.accountBalanceEntries(db,{page:1},options).items[0].balanceMinor).toBe(45000);
 db.prepare('UPDATE Expenses SET balance_due_minor=44999').run();expect(()=>report.accountBalanceSummary(db,{},options)).toThrow(/do not reconcile/);
});test("invalid expense rolls back without cash movement",()=>{expect(()=>new ExpensesService(db).post({categoryId:category.id,amountMinor:-1,description:"Bad",idempotencyKey:"bad"})).toThrow(/positive/);expect(db.prepare("SELECT COUNT(*) count FROM MoneyMovements").get().count).toBe(0);});});
