const fs=require("fs"),os=require("os"),path=require("path");
const {openDatabase}=require("../infrastructure/sqlite/database");
const {ProductsRepository}=require("../infrastructure/sqlite/repositories/products");
const {ProductUnitsRepository}=require("../infrastructure/sqlite/repositories/product-units");
const {OpeningStockImportService}=require("../infrastructure/sqlite/services/opening-stock-import");

describe("batch-aware opening stock import",()=>{let dir,db,product,other;beforeEach(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),"to-opening-"));db=openDatabase({filename:path.join(dir,"db.sqlite3")});const products=new ProductsRepository(db),units=new ProductUnitsRepository(db);product=products.create({sku:"MED-1",barcode:"111",name:"Medicine",productType:"medicine",baseUnit:"tablet",defaultSalePriceMinor:120});units.configure(product.id,[{unitName:"tablet",baseQuantity:1,sellingPriceMinor:120,isDefaultSaleUnit:true},{unitName:"box",baseQuantity:20,sellingPriceMinor:2000}]);other=products.create({sku:"GEN-1",name:"General",productType:"general",baseUnit:"piece"});units.configure(other.id,[{unitName:"piece",baseQuantity:1,sellingPriceMinor:100,isDefaultSaleUnit:true}]);});afterEach(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});
test("previews and atomically posts batch quantity in base units without a purchase",()=>{const service=new OpeningStockImportService(db);const preview=service.preview({rows:[{sku:"MED-1",batch_number:"B-1",expiry_date:"12/2028",entry_date:"12/09/2026",unit:"box",quantity:3,unit_cost:5}],sourceName:"opening.xlsx"});expect(preview).toMatchObject({validRows:1,errorRows:0});expect(preview.rows[0].normalized).toMatchObject({expiryDate:"2028-12-31",baseQuantity:60,unitCostMinor:500});const result=service.commit(preview.jobId);expect(result.committedRows).toBe(1);expect(db.prepare("SELECT quantity_on_hand,opening_quantity FROM ProductBatches WHERE product_id=?").get(product.id)).toMatchObject({quantity_on_hand:60,opening_quantity:60});expect(db.prepare("SELECT movement_type,quantity_delta FROM InventoryMovements WHERE product_id=?").get(product.id)).toMatchObject({movement_type:"opening",quantity_delta:60});expect(db.prepare("SELECT COUNT(*) AS count FROM Purchases").get().count).toBe(0);expect(db.prepare("SELECT action FROM AuditLog WHERE entity_id=?").get(String(preview.jobId)).action).toBe("opening_stock.import");expect(()=>service.commit(preview.jobId)).toThrow(/not available/);});
test("locks only products with prior movements and preserves other new products",()=>{const now=new Date().toISOString();const batch=db.prepare(`INSERT INTO ProductBatches(product_id,batch_number,expiry_date,unit_cost_minor,sale_price_minor,quantity_on_hand,received_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)`).run(other.id,null,null,0,100,1,now,now,now).lastInsertRowid;db.prepare(`INSERT INTO InventoryMovements(product_id,batch_id,movement_type,quantity_delta,reference_type,occurred_at) VALUES (?,?,'opening',1,'manual',?)`).run(other.id,batch,now);const preview=new OpeningStockImportService(db).preview({rows:[{sku:"GEN-1",unit:"piece",quantity:2,unit_cost:1},{sku:"MED-1",batch_number:"B-2",expiry_date:"2028-01-01",unit:"tablet",quantity:2,unit_cost:1}]});expect(preview).toMatchObject({validRows:1,errorRows:1});expect(preview.rows[0].errors.join(" ")).toMatch(/locked/);expect(preview.rows[1].action).toBe("insert");expect(()=>new OpeningStockImportService(db).commit(preview.jobId)).toThrow(/validation errors/);expect(db.prepare("SELECT COUNT(*) AS count FROM InventoryMovements WHERE product_id=?").get(product.id).count).toBe(0);});
test("requires medicine batch and expiry, configured unit, and positive quantity",()=>{const preview=new OpeningStockImportService(db).preview({rows:[{sku:"MED-1",unit:"carton",quantity:0,unit_cost:-1}]});expect(preview.errorRows).toBe(1);expect(preview.rows[0].errors.join(" ")).toMatch(/batch_number.*expiry_date.*quantity.*unit_cost.*unit is not configured/);});
});
