const fs=require("fs"); const os=require("os"); const path=require("path"); const http=require("http"); const express=require("express");
const {openDatabase}=require("../infrastructure/sqlite/database"); const {ProductsRepository}=require("../infrastructure/sqlite/repositories/products"); const {ProductUnitsRepository}=require("../infrastructure/sqlite/repositories/product-units"); const {createSqliteSalesRouter}=require("../api/v2/sqlite-sales");

describe("SQLite sales v2 API",()=>{let dir,db,server,baseUrl,product;
  beforeEach(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),"techorbit-api-"));db=openDatabase({filename:path.join(dir,"db.sqlite3")});product=new ProductsRepository(db).create({name:"Panadol",genericName:"Paracetamol",baseUnit:"tablet"});new ProductUnitsRepository(db).configure(product.id,[{unitName:"tablet",baseQuantity:1,sellingPriceMinor:125,isDefaultSaleUnit:true}]);const now=new Date().toISOString();db.prepare(`INSERT INTO ProductBatches(product_id,batch_number,expiry_date,unit_cost_minor,sale_price_minor,quantity_on_hand,received_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)`).run(product.id,"B-1","2028-01-01",50,125,20,"2026-01-01",now,now);const app=express();app.use(express.json());app.use("/api/v2/sales",createSqliteSalesRouter({getDatabase:()=>db}));server=http.createServer(app);await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));baseUrl=`http://127.0.0.1:${server.address().port}`;});
  afterEach(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(db)db.close();if(dir)fs.rmSync(dir,{recursive:true,force:true});});
  test("posts, searches, reads and renders immutable receipt data",async()=>{const payload={invoiceNumber:"TO-100",idempotencyKey:"key-100",soldAt:"2026-09-12T10:00:00Z",paymentMethod:"cash",items:[{productId:product.id,saleUnit:"tablet",quantity:2}]};let response=await fetch(`${baseUrl}/api/v2/sales`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});expect(response.status).toBe(201);const posted=await response.json();response=await fetch(`${baseUrl}/api/v2/sales?invoiceNumber=TO-100&product=Panadol`);expect((await response.json())).toHaveLength(1);response=await fetch(`${baseUrl}/api/v2/sales/${posted.saleId}`);expect((await response.json()).items[0].allocations).toHaveLength(1);db.prepare("UPDATE Products SET name='Changed Name' WHERE id=?").run(product.id);response=await fetch(`${baseUrl}/api/v2/sales/${posted.saleId}/receipt`);const receipt=await response.json();expect(receipt.items[0].productName).toBe("Panadol");expect(receipt.totals.finalTotalMinor).toBe(posted.finalTotalMinor);});
  test("returns safe errors for invalid and duplicate submissions",async()=>{let response=await fetch(`${baseUrl}/api/v2/sales`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});expect(response.status).toBe(422);expect((await response.json()).error).toBe("SALE_VALIDATION_FAILED");const payload={invoiceNumber:"TO-2",idempotencyKey:"same",paymentMethod:"cash",items:[{productId:product.id,saleUnit:"tablet",quantity:1}]};await fetch(`${baseUrl}/api/v2/sales`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});response=await fetch(`${baseUrl}/api/v2/sales`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});expect(response.status).toBe(409);});
});
