const {CustomerAccountsService}=require('../../infrastructure/sqlite/services/customer-accounts');
const {PurchasePaymentsService}=require('../../infrastructure/sqlite/services/purchase-payments');
const {ExpensesService}=require('../../infrastructure/sqlite/services/expenses');
const pageInput=input=>({page:Math.max(1,Number(input?.page)||1),pageSize:Math.min(100,Math.max(10,Number(input?.pageSize)||25))});
const like=value=>`%${String(value||'').trim()}%`;
const day=value=>String(value||'').slice(0,10);
const assertKey=value=>{const key=String(value||'');if(!/^TO-[a-f0-9-]{36}$/.test(key))throw Error('Invalid transaction reference');return key;};

class AccountsDesktop{
 constructor(db){this.db=db;}
 customers(input={}){
  const {page,pageSize}=pageInput(input),q=like(input.q),offset=(page-1)*pageSize;
  const base=`FROM Customers c WHERE c.active=1 AND (?='%%' OR c.name LIKE ? OR c.phone LIKE ? OR c.normalized_phone LIKE ?)`;
  const params=[q,q,q,q],total=Number(this.db.prepare(`SELECT COUNT(DISTINCT c.id) total ${base}`).get(...params).total);
  const items=this.db.prepare(`SELECT c.id,c.name,c.phone,c.normalized_phone,(SELECT COUNT(*) FROM Sales s WHERE s.customer_id=c.id) invoice_count,(SELECT COALESCE(SUM(r.balance_minor),0) FROM Receivables r WHERE r.customer_id=c.id) outstanding_minor ${base} ORDER BY c.name,c.id LIMIT ? OFFSET ?`).all(...params,pageSize,offset);
  return{items,total,page,pageSize};
 }
 customerDetail(input={}){
  const id=Number(input.id),customer=this.db.prepare('SELECT id,name,phone,normalized_phone,created_at FROM Customers WHERE id=? AND active=1').get(id);if(!customer)throw Error('Active customer was not found');
  const invoices=this.db.prepare(`SELECT s.id,s.invoice_number,s.sold_at,s.final_total_minor,s.amount_paid_minor,s.balance_due_minor,s.payment_status,s.due_date FROM Sales s WHERE s.customer_id=? ORDER BY s.sold_at DESC,s.id DESC LIMIT 100`).all(id);
  const collections=this.db.prepare(`SELECT rp.id,rp.receivable_id,rp.amount_minor,rp.method,rp.collected_at,s.invoice_number FROM ReceivablePayments rp JOIN Sales s ON s.id=rp.sale_id WHERE rp.customer_id=? ORDER BY rp.collected_at DESC,rp.id DESC LIMIT 100`).all(id);
  const returns=this.db.prepare(`SELECT sr.id,sr.total_minor,sr.receivable_credit_minor,sr.refund_minor,sr.returned_at,s.invoice_number FROM SaleReturns sr JOIN Sales s ON s.id=sr.sale_id WHERE sr.customer_id=? ORDER BY sr.returned_at DESC,sr.id DESC LIMIT 100`).all(id);
  const summary=this.db.prepare(`SELECT COUNT(*) invoice_count,COALESCE(SUM(final_total_minor),0) invoiced_minor,COALESCE(SUM(amount_paid_minor),0) collected_minor,COALESCE(SUM(balance_due_minor),0) outstanding_minor FROM Sales WHERE customer_id=? AND status='posted'`).get(id);
  return{customer,summary,invoices,collections,returns};
 }
 dues(input={}){
  const {page,pageSize}=pageInput(input),type=['customer','supplier','vendor'].includes(input.type)?input.type:'all',status=['open','overdue','paid'].includes(input.status)?input.status:'open',q=like(input.q),today=day(new Date().toISOString()),offset=(page-1)*pageSize;
  const union=`SELECT 'customer' type,r.id,c.name party,s.invoice_number reference,s.sold_at origin_date,r.due_date,r.original_minor,s.amount_paid_minor paid_minor,r.balance_minor,r.status,(SELECT COUNT(*) FROM ReceivablePayments x WHERE x.receivable_id=r.id) payment_count,1 settleable FROM Receivables r LEFT JOIN Customers c ON c.id=r.customer_id LEFT JOIN Sales s ON r.source_type='sale' AND s.id=CAST(r.source_id AS INTEGER)
   UNION ALL SELECT 'supplier',p.id,su.name,COALESCE(pu.invoice_number,'Account #'||p.id),COALESCE(pu.purchased_at,p.created_at),p.due_date,p.original_minor,COALESCE(pu.amount_paid_minor,p.original_minor-p.balance_minor),p.balance_minor,p.status,(SELECT COUNT(*) FROM PurchasePayments x WHERE x.payable_id=p.id),CASE WHEN p.source_type='purchase' AND pu.id IS NOT NULL THEN 1 ELSE 0 END FROM Payables p LEFT JOIN Suppliers su ON su.id=p.supplier_id LEFT JOIN Purchases pu ON p.source_type='purchase' AND pu.id=CAST(p.source_id AS INTEGER)
   UNION ALL SELECT 'vendor',ep.id,v.name,COALESCE(e.reference,'Expense #'||e.id),e.expense_date,ep.due_date,e.amount_minor,e.amount_paid_minor,ep.balance_minor,ep.status,(SELECT COUNT(*) FROM ExpensePayments x WHERE x.payable_id=ep.id),1 FROM ExpensePayables ep JOIN Vendors v ON v.id=ep.vendor_id JOIN Expenses e ON e.id=ep.expense_id`;
  const clauses=["(?='all' OR type=?)","(?='%%' OR party LIKE ? OR reference LIKE ?)"];const params=[type,type,q,q,q];
  if(status==='open')clauses.push('balance_minor>0');else if(status==='overdue'){clauses.push('balance_minor>0 AND due_date IS NOT NULL AND due_date<?');params.push(today);}else clauses.push("balance_minor=0 AND status='paid'");
  const where=clauses.join(' AND '),total=Number(this.db.prepare(`SELECT COUNT(*) total FROM (${union}) WHERE ${where}`).get(...params).total);
  const items=this.db.prepare(`SELECT *,CASE WHEN balance_minor>0 AND due_date IS NOT NULL AND due_date<? THEN 1 ELSE 0 END overdue FROM (${union}) WHERE ${where} ORDER BY overdue DESC,due_date IS NULL,due_date,origin_date DESC,id DESC LIMIT ? OFFSET ?`).all(today,...params,pageSize,offset);
  return{items,total,page,pageSize};
 }
 history(input={}){
  const id=Number(input.id),type=input.type;if(type==='customer')return this.db.prepare(`SELECT rp.id,rp.amount_minor,rp.method,rp.reference,rp.collected_at occurred_at,(SELECT a.occurred_at FROM AuditLog a WHERE a.action='receivable.payment' AND a.entity_type='receivable' AND a.entity_id=CAST(rp.receivable_id AS TEXT) AND CAST(json_extract(a.new_json,'$.paymentId') AS INTEGER)=rp.id ORDER BY a.id LIMIT 1) audit_at,(SELECT a.role_code FROM AuditLog a WHERE a.action='receivable.payment' AND a.entity_type='receivable' AND a.entity_id=CAST(rp.receivable_id AS TEXT) AND CAST(json_extract(a.new_json,'$.paymentId') AS INTEGER)=rp.id ORDER BY a.id LIMIT 1) role_code FROM ReceivablePayments rp WHERE rp.receivable_id=? ORDER BY rp.collected_at DESC,rp.id DESC`).all(id);
  if(type==='supplier')return this.db.prepare(`SELECT pp.id,pp.amount_minor,pp.method,pp.reference,pp.paid_at occurred_at,(SELECT a.occurred_at FROM AuditLog a WHERE a.action='payable.payment' AND a.entity_type='payable' AND a.entity_id=CAST(pp.payable_id AS TEXT) AND CAST(json_extract(a.new_json,'$.paymentId') AS INTEGER)=pp.id ORDER BY a.id LIMIT 1) audit_at,(SELECT a.role_code FROM AuditLog a WHERE a.action='payable.payment' AND a.entity_type='payable' AND a.entity_id=CAST(pp.payable_id AS TEXT) AND CAST(json_extract(a.new_json,'$.paymentId') AS INTEGER)=pp.id ORDER BY a.id LIMIT 1) role_code FROM PurchasePayments pp WHERE pp.payable_id=? ORDER BY pp.paid_at DESC,pp.id DESC`).all(id);
  if(type==='vendor')return this.db.prepare(`SELECT ep.id,ep.amount_minor,ep.method,ep.reference,ep.paid_at occurred_at,(SELECT a.occurred_at FROM AuditLog a WHERE a.action='expense.payable.payment' AND a.entity_type='expense' AND a.entity_id=CAST(ep.expense_id AS TEXT) AND CAST(json_extract(a.new_json,'$.paymentId') AS INTEGER)=ep.id ORDER BY a.id LIMIT 1) audit_at,(SELECT a.role_code FROM AuditLog a WHERE a.action='expense.payable.payment' AND a.entity_type='expense' AND a.entity_id=CAST(ep.expense_id AS TEXT) AND CAST(json_extract(a.new_json,'$.paymentId') AS INTEGER)=ep.id ORDER BY a.id LIMIT 1) role_code FROM ExpensePayments ep WHERE ep.payable_id=? ORDER BY ep.paid_at DESC,ep.id DESC`).all(id);
  throw Error('Unknown account type');
 }
 collect(input,user){return new CustomerAccountsService(this.db).collect({...input,idempotencyKey:assertKey(input.idempotencyKey),createdBy:user.id,roleCode:user.roleCode,deviceId:'modern-desktop'});}
 paySupplier(input,user){return new PurchasePaymentsService(this.db).post({...input,idempotencyKey:assertKey(input.idempotencyKey),createdBy:user.id,roleCode:user.roleCode,deviceId:'modern-desktop',reason:'Supplier payment from Accounts workspace'});}
 payVendor(input,user){return new ExpensesService(this.db).settle({...input,idempotencyKey:assertKey(input.idempotencyKey),createdBy:user.id,roleCode:user.roleCode,deviceId:'modern-desktop',reason:'Vendor payment from Accounts workspace'});}
 metadata(){return{categories:this.db.prepare('SELECT id,name FROM ExpenseCategories WHERE active=1 ORDER BY name').all(),vendors:this.db.prepare(`SELECT v.id,v.name,v.phone,v.active,COALESCE(SUM(ep.balance_minor),0) balance_minor FROM Vendors v LEFT JOIN ExpensePayables ep ON ep.vendor_id=v.id GROUP BY v.id ORDER BY v.name`).all()};}
 saveVendor(input,user){const name=String(input.name||'').trim(),phone=String(input.phone||'').trim()||null;if(name.length<2||name.length>160)throw Error('Vendor name must be 2–160 characters');if(phone&&phone.length>50)throw Error('Vendor phone must be 50 characters or fewer');const now=new Date().toISOString();return this.db.transaction(()=>{let row,before=null;if(input.id){const id=Number(input.id);before=this.db.prepare('SELECT name,active FROM Vendors WHERE id=?').get(id);if(!before)throw Error('Vendor was not found');this.db.prepare('UPDATE Vendors SET name=?,phone=?,active=?,updated_at=? WHERE id=?').run(name,phone,input.active===false?0:1,now,id);row=this.db.prepare('SELECT * FROM Vendors WHERE id=?').get(id);}else{const id=Number(this.db.prepare('INSERT INTO Vendors(name,phone,created_at,updated_at) VALUES (?,?,?,?)').run(name,phone,now,now).lastInsertRowid);row=this.db.prepare('SELECT * FROM Vendors WHERE id=?').get(id);}this.db.prepare("INSERT INTO AuditLog(occurred_at,user_id,role_code,action,entity_type,entity_id,previous_json,new_json,reason,device_id) VALUES (?,?,?,'vendor.save','vendor',?,?,?,?,'modern-desktop')").run(now,user.id,user.roleCode,String(row.id),before?JSON.stringify({name:before.name,active:Boolean(before.active)}):null,JSON.stringify({name:row.name,active:Boolean(row.active)}),before?'Vendor profile updated':'Vendor created');return row;})();}
 expenses(input={}){const {page,pageSize}=pageInput(input),q=like(input.q),offset=(page-1)*pageSize,params=[q,q,q];const where="WHERE (?='%%' OR e.description LIKE ? OR COALESCE(e.reference,'') LIKE ?)";const total=Number(this.db.prepare(`SELECT COUNT(*) total FROM Expenses e ${where}`).get(...params).total);const items=this.db.prepare(`SELECT e.id,e.expense_date,e.description,e.reference,e.amount_minor,e.amount_paid_minor,e.balance_due_minor,e.method,e.due_date,e.status,c.name category_name,COALESCE(v.name,e.vendor) vendor_name,ep.id payable_id FROM Expenses e JOIN ExpenseCategories c ON c.id=e.category_id LEFT JOIN Vendors v ON v.id=e.vendor_id LEFT JOIN ExpensePayables ep ON ep.expense_id=e.id ${where} ORDER BY e.expense_date DESC,e.id DESC LIMIT ? OFFSET ?`).all(...params,pageSize,offset);return{items,total,page,pageSize};}
 postExpense(input,user){return new ExpensesService(this.db).post({...input,idempotencyKey:assertKey(input.idempotencyKey),createdBy:user.id,roleCode:user.roleCode,deviceId:'modern-desktop'});}
 voidExpense(input,user){return new ExpensesService(this.db).void({...input,createdBy:user.id,roleCode:user.roleCode,deviceId:'modern-desktop'});}
}
module.exports={AccountsDesktop};
