import {useEffect,useState} from 'react';
import type {DailyClosingInput,DailyClosingSummary,DailyClosingRow} from './contracts';
import {money,dateLabel} from './shared';
export function DailyClosingReport(){
 const initial:DailyClosingInput={range:'1m',basis:'latest',dateBasis:'closed'};
 const [draft,setDraft]=useState(initial),[applied,setApplied]=useState(initial),[page,setPage]=useState(1);
 const [summary,setSummary]=useState<DailyClosingSummary|null>(null),[entries,setEntries]=useState<{hasMore:boolean;items:DailyClosingRow[]}|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setBusy(true);setError('');Promise.all([window.pharmacy.dailyClosingSummary(applied),window.pharmacy.dailyClosingEntries({...applied,page})]).then(([s,e])=>{if(active){setSummary(s);setEntries(e)}}).catch(e=>{if(active){setSummary(null);setEntries(null);setError((e as Error).message)}}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[applied,page]);
 return <>
  <div className="page-title"><h1>Daily Closing Report</h1>{(['csv','xlsx','pdf'] as const).map(format=><button key={format} disabled={busy||!summary} onClick={async()=>{try{setError('');const r=await window.pharmacy.dailyClosingExport({...applied,format});if(r.saved)setNotice(`${format.toUpperCase()} daily closing report saved.`)}catch(e){setError((e as Error).message)}}}>Export {format.toUpperCase()}</button>)}</div>
  <section className="panel"><h2>Filters</h2><form onSubmit={e=>{e.preventDefault();setPage(1);setNotice('');setApplied({...draft})}}><div className="closing-form">
   <label>Closing range<select aria-label="Closing range" value={draft.range} onChange={e=>setDraft({...draft,range:e.target.value})}>{[['7d','7 Days'],['1m','1 Month'],['6m','6 Months'],['1y','1 Year'],['custom','Custom']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
   {draft.range==='custom'&&<><label>Closing report from<input type="date" value={draft.from||''} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>Closing report to<input type="date" value={draft.to||''} onChange={e=>setDraft({...draft,to:e.target.value})}/></label></>}
   <label>Snapshot version<select aria-label="Snapshot version" value={draft.basis} onChange={e=>setDraft({...draft,basis:e.target.value as DailyClosingInput['basis']})}><option value="latest">Latest saved revision</option><option value="original">Original closing</option></select></label>
   <label>Closing date basis<select aria-label="Closing date basis" value={draft.dateBasis} onChange={e=>setDraft({...draft,dateBasis:e.target.value as DailyClosingInput['dateBasis']})}><option value="closed">Actual closing date</option><option value="opened">Business day opening date</option></select></label>
   <label>Closed by<input maxLength={100} value={draft.closer||''} onChange={e=>setDraft({...draft,closer:e.target.value})}/></label><label>Counter/device<input maxLength={100} value={draft.device||''} onChange={e=>setDraft({...draft,device:e.target.value})}/></label>
   </div><button className="primary">Run report</button></form><small>{summary?.scope}</small>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>
  <section className="panel"><h2>Closing totals</h2>{summary&&<><p>Closed days: {summary.totals.dayCount} | Shifts: {summary.totals.shiftCount}</p><p>Cash variance: PKR {money(summary.totals.cashVarianceMinor)} | Bank/wallet variance: PKR {money(summary.totals.digitalVarianceMinor)} | Actual savings transferred: PKR {money(summary.totals.savingsTransferredMinor)}</p></>}</section>
  <section className="panel"><h2>Saved closing detail</h2>{entries?.items.length?entries.items.map(x=><details key={x.id}><summary>Business day #{x.id} | Opened {x.openedDate} | Closed {x.closedDate} | Revision {x.snapshot.revisionNumber||0} of {x.revisionCount}</summary><p>{dateLabel(x.snapshot.openedAt)} to {dateLabel(x.snapshot.closedAt!)} | Closed by {x.closer}</p><p>Expected cash: {money(x.snapshot.cashExpectedMinor)} | Counted cash: {money(x.snapshot.cashCountedMinor||0)} | Cash variance: {money(x.snapshot.cashVarianceMinor||0)}</p><p>Reason: {x.snapshot.revisionReason||x.snapshot.reason||'No variance reason recorded'}</p><table><thead><tr><th>Account</th><th>Kind</th><th>Expected net</th><th>Actual net</th><th>Variance</th></tr></thead><tbody>{x.snapshot.accounts.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.kind}</td><td>{money(a.expectedNetMinor)}</td><td>{money(a.actualNetMinor||0)}</td><td>{money(a.varianceMinor||0)}</td></tr>)}</tbody></table><p>Shifts: {x.snapshot.shifts.map(s=>`#${s.id} ${s.device_id} (${s.status})`).join(', ')}</p>{x.revisions.map(r=><p key={r.revision_number}>Revision {r.revision_number}: {r.reason} ({dateLabel(r.revised_at)})</p>)}</details>):<p>No saved closings match these filters.</p>}<div className="segmented"><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={busy||!entries?.hasMore} onClick={()=>setPage(page+1)}>Next</button></div></section>
 </>;
}
