import {useEffect,useState} from 'react';
import {Search,RefreshCw,Eye} from 'lucide-react';
import type {InventoryBatch,InventoryMovement,InventoryResult} from './contracts';
import {Dialog,money} from './shared';

const quantity=(value:number)=>Number(value).toLocaleString(undefined,{maximumFractionDigits:3});
const date=(value:string|null)=>value||'No expiry';

export function Inventory(){
 const [q,setQ]=useState(''),[stock,setStock]=useState('all'),[expiry,setExpiry]=useState('all'),[page,setPage]=useState(1),[version,reload]=useState(0);
 const [result,setResult]=useState<InventoryResult>({items:[],total:0,page:1,pageSize:25,costVisible:false,asOfDate:''}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [detail,setDetail]=useState<{batch:InventoryBatch;movements:InventoryMovement[];costVisible:boolean}|null>(null),[detailError,setDetailError]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');const timer=setTimeout(()=>window.pharmacy.inventoryList({q,stock,expiry,page}).then(data=>{if(live)setResult(data)}).catch(e=>{if(live){setError(e.message);setResult(r=>({...r,items:[],total:0}))}}).finally(()=>{if(live)setLoading(false)}),150);return()=>{live=false;clearTimeout(timer)}},[q,stock,expiry,page,version]);
 const open=async(batchId:number)=>{setDetailError('');try{setDetail(await window.pharmacy.inventoryDetail({batchId}))}catch(e){setDetailError((e as Error).message)}};
 const change=(setter:(value:string)=>void)=>(event:React.ChangeEvent<HTMLSelectElement>)=>{setter(event.target.value);setPage(1)};
 return <section className="inventory-page"><div className="page-title"><div><h1>Inventory</h1><p>Batch-level physical and sellable stock as of {result.asOfDate||'today'}. Expired stock remains visible but cannot be sold.</p></div><button onClick={()=>reload(v=>v+1)} disabled={loading}><RefreshCw size={16}/> Refresh</button></div>
  <div className="inventory-summary"><article className="panel"><small>Matching batches</small><strong>{result.total}</strong></article><article className="panel"><small>Page physical base units</small><strong>{quantity(result.items.reduce((sum,row)=>sum+row.physicalQuantity,0))}</strong></article><article className="panel"><small>Page sellable base units</small><strong>{quantity(result.items.reduce((sum,row)=>sum+row.sellableQuantity,0))}</strong></article><article className="panel"><small>Cost visibility</small><strong>{result.costVisible?'Authorized':'Protected'}</strong></article></div>
  <div className="inventory-toolbar"><label><Search size={17}/><input aria-label="Search inventory" placeholder="Medicine, generic, manufacturer, SKU or batch" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><select aria-label="Stock status filter" value={stock} onChange={change(setStock)}><option value="all">All stock statuses</option><option value="in_stock">In stock</option><option value="low_stock">Low stock</option><option value="out_of_stock">Out of stock</option></select><select aria-label="Expiry status filter" value={expiry} onChange={change(setExpiry)}><option value="all">All expiry statuses</option><option value="expired">Expired</option><option value="30">Within 30 days</option><option value="60">Within 60 days</option><option value="90">Within 90 days</option><option value="safe">Safe</option><option value="none">No expiry</option></select></div>
  {error&&<p role="alert" className="error">{error}</p>}{detailError&&<p role="alert" className="error">{detailError}</p>}
  <div className="panel inventory-table"><table><thead><tr><th>Medicine / batch</th><th>Supplier</th><th>Expiry</th><th>Physical</th><th>Sellable</th><th>Stock status</th>{result.costVisible&&<><th>Effective cost</th><th>Stock value</th></>}<th>Action</th></tr></thead><tbody>{!loading&&result.items.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>{row.genericName||'No generic'} · {row.batchNumber||'No batch'} · #{row.id}</small></td><td>{row.supplierName||'Not linked'}</td><td>{date(row.expiryDate)}<small className={'status-tag '+row.expiryStatus.toLowerCase().replaceAll(' ','-')}>{row.expiryStatus}</small></td><td>{quantity(row.physicalQuantity)} {row.baseUnit}</td><td>{quantity(row.sellableQuantity)} {row.baseUnit}</td><td><span className={'status-tag '+row.stockStatus.toLowerCase().replaceAll(' ','-')}>{row.stockStatus}</span></td>{result.costVisible&&<><td>{money(row.effectiveCostMinor||0)}</td><td>{money(row.stockValueMinor||0)}</td></>}<td><button aria-label={'View batch '+row.id} onClick={()=>open(row.id)}><Eye size={15}/> View</button></td></tr>)}</tbody></table>{loading?<p role="status">Loading inventory…</p>:!result.items.length&&<p>No batches match these filters.</p>}</div>
  <div className="master-pagination"><button disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{result.total} batches · Page {page} of {Math.max(1,Math.ceil(result.total/result.pageSize))}</span><button disabled={loading||page*result.pageSize>=result.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  {detail&&<Dialog title={'Batch '+(detail.batch.batchNumber||'#'+detail.batch.id)} onClose={()=>setDetail(null)}><div className="inventory-detail"><div className="inventory-detail-head"><div><h3>{detail.batch.name}</h3><p>{detail.batch.genericName||'No generic'} · {detail.batch.manufacturer||'No manufacturer'}</p></div><span className={'status-tag '+detail.batch.stockStatus.toLowerCase().replaceAll(' ','-')}>{detail.batch.stockStatus}</span></div><dl>{[['Product ID','#'+detail.batch.productId],['Supplier',detail.batch.supplierName||'Not linked'],['Manufactured',detail.batch.manufacturingDate||'Not recorded'],['Expiry',detail.batch.expiryDate||'Not recorded'],['Physical',quantity(detail.batch.physicalQuantity)+' '+detail.batch.baseUnit],['Sellable',quantity(detail.batch.sellableQuantity)+' '+detail.batch.baseUnit],['Expiry status',detail.batch.expiryStatus]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h3>Quantity history</h3><div className="inventory-quantities">{[['Opening',detail.batch.openingQuantity],['Purchased',detail.batch.purchasedQuantity],['Bonus',detail.batch.bonusQuantity],['Sold',detail.batch.soldQuantity],['Customer returns',detail.batch.customerReturnQuantity],['Supplier returns',detail.batch.supplierReturnQuantity],['Adjustments',detail.batch.adjustmentQuantity],['Disposed',detail.batch.disposedQuantity]].map(([label,value])=><div key={String(label)}><small>{label}</small><strong>{quantity(Number(value))}</strong></div>)}</div>{detail.costVisible&&<p><strong>Effective cost:</strong> {money(detail.batch.effectiveCostMinor||0)} · <strong>Estimated stock value:</strong> {money(detail.batch.stockValueMinor||0)}</p>}<h3>Latest movements</h3><div className="movement-list">{detail.movements.length?detail.movements.map(m=><article key={m.id}><div><strong>{m.movement_type.replaceAll('_',' ')}</strong><small>{m.occurred_at} · {m.reference_type}{m.reference_id?' #'+m.reference_id:''}</small></div><b className={m.quantity_delta<0?'negative':''}>{m.quantity_delta>0?'+':''}{quantity(m.quantity_delta)}</b></article>):<p>No stock movements recorded for this batch.</p>}</div></div></Dialog>}
 </section>
}
