import {useEffect,useState} from 'react';
import {Download,FileUp,Plus} from 'lucide-react';
import type {OpeningStockPreview,OpeningStockProduct} from './contracts';
import {Dialog,money} from './shared';

const today=()=>new Date().toISOString().slice(0,10);
const toBase64=async(file:File)=>{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)};
const download=(name:string,mime:string,base64:string)=>{const a=document.createElement('a');a.href=`data:${mime};base64,${base64}`;a.download=name;a.click()};

export function OpeningStock({onClose,onCommitted}:{onClose:()=>void;onCommitted:()=>void}){
 const [mode,setMode]=useState<'manual'|'file'>('manual'),[q,setQ]=useState(''),[products,setProducts]=useState<OpeningStockProduct[]>([]),[productId,setProductId]=useState<number|null>(null);
 const [entryDate,setEntryDate]=useState(today()),[batchNumber,setBatchNumber]=useState(''),[expiryDate,setExpiryDate]=useState(''),[unit,setUnit]=useState(''),[quantity,setQuantity]=useState(''),[unitCost,setUnitCost]=useState(''),[notes,setNotes]=useState('');
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<OpeningStockPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 useEffect(()=>{let live=true;const timer=setTimeout(()=>window.pharmacy.openingStockProducts({q}).then(rows=>{if(live)setProducts(rows)}).catch(e=>{if(live)setError(e.message)}),150);return()=>{live=false;clearTimeout(timer)}},[q]);
 const selected=products.find(p=>p.id===productId)||null;
 useEffect(()=>{if(selected&&!selected.units.some(u=>u.unit_name===unit))setUnit(selected.units[0]?.unit_name||selected.base_unit)},[selected,unit]);
 const resetPreview=()=>{setPreview(null);setError('');setStatus('')};
 const previewManual=async(event:React.FormEvent)=>{event.preventDefault();if(!selected)return;setBusy(true);resetPreview();try{setPreview(await window.pharmacy.openingStockPreviewManual({productId:selected.id,entryDate,batchNumber,expiryDate,unit,quantity:Number(quantity),unitCost:Number(unitCost),notes}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const previewFile=async()=>{if(!file)return;setBusy(true);resetPreview();try{setPreview(await window.pharmacy.openingStockPreviewFile({name:file.name,base64:await toBase64(file)}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const commit=async()=>{if(!preview||preview.errorRows)return;setBusy(true);setError('');try{const result=await window.pharmacy.openingStockCommit({jobId:preview.jobId});setStatus(`${result.committedRows} opening-stock row${result.committedRows===1?'':'s'} committed.`);onCommitted()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const getTemplate=async()=>{setBusy(true);setError('');try{const result=await window.pharmacy.openingStockTemplate();download(result.name,result.mime,result.base64)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <Dialog title="Opening stock" onClose={onClose}><div className="opening-stock"><p>Use this only before a product has purchase, sale, return, adjustment or disposal history. Preview is required before commit.</p><div className="segmented"><button aria-pressed={mode==='manual'} onClick={()=>{setMode('manual');resetPreview()}}><Plus size={15}/> Manual entry</button><button aria-pressed={mode==='file'} onClick={()=>{setMode('file');resetPreview()}}><FileUp size={15}/> Excel / CSV import</button></div>
 {mode==='manual'?<form className="opening-manual" onSubmit={previewManual}><label>Find product<input aria-label="Find opening stock product" placeholder="Name, generic, SKU or barcode" value={q} onChange={e=>{setQ(e.target.value);setProductId(null);resetPreview()}}/></label><label>Product<select aria-label="Opening stock product" required value={productId??''} onChange={e=>{setProductId(Number(e.target.value)||null);resetPreview()}}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id} disabled={p.locked}>{p.name}{p.locked?' — opening stock locked':''}</option>)}</select></label>{selected&&<><p className={selected.locked?'error':'opening-note'}>{selected.locked?'Opening stock is locked because this product already has inventory history.':`${selected.generic_name||'No generic'} · ${selected.product_type} · Base unit ${selected.base_unit}`}</p><div className="opening-fields"><label>Entry date<input aria-label="Opening stock entry date" type="date" required value={entryDate} onChange={e=>{setEntryDate(e.target.value);resetPreview()}}/></label><label>Batch number<input aria-label="Opening stock batch number" required={selected.product_type==='medicine'} value={batchNumber} onChange={e=>{setBatchNumber(e.target.value);resetPreview()}}/></label><label>Expiry date or MM/YYYY<input aria-label="Opening stock expiry" placeholder="YYYY-MM-DD or MM/YYYY" required={selected.product_type==='medicine'} value={expiryDate} onChange={e=>{setExpiryDate(e.target.value);resetPreview()}}/></label><label>Unit<select aria-label="Opening stock unit" required value={unit} onChange={e=>{setUnit(e.target.value);resetPreview()}}>{selected.units.map(u=><option key={u.unit_name} value={u.unit_name}>{u.unit_name} × {u.base_quantity} {selected.base_unit}</option>)}</select></label><label>Quantity<input aria-label="Opening stock quantity" type="number" min="0" step="any" required value={quantity} onChange={e=>{setQuantity(e.target.value);resetPreview()}}/></label><label>Unit cost PKR<input aria-label="Opening stock unit cost" type="number" min="0" step="0.01" required value={unitCost} onChange={e=>{setUnitCost(e.target.value);resetPreview()}}/></label><label className="wide">Notes<input aria-label="Opening stock notes" maxLength={500} value={notes} onChange={e=>{setNotes(e.target.value);resetPreview()}}/></label></div><button className="primary" type="submit" disabled={busy||selected.locked}>Preview manual entry</button></>}</form>:<div className="opening-file"><button onClick={getTemplate} disabled={busy}><Download size={15}/> Download template</button><label>Opening-stock file<input aria-label="Opening stock file" type="file" accept=".xlsx,.csv" onChange={e=>{setFile(e.target.files?.[0]||null);resetPreview()}}/></label><button className="primary" onClick={previewFile} disabled={busy||!file}>Preview file</button><small>Maximum 4 MB. XLSX and CSV are accepted. Keep SKU or barcode as text.</small></div>}
 {preview&&<section className="opening-preview"><h3>Preview</h3><p>{preview.validRows} valid · {preview.errorRows} errors · {preview.totalRows} total</p><div><table><thead><tr><th>Row</th><th>Product</th><th>Batch / expiry</th><th>Entered</th><th>Base quantity</th><th>Unit cost</th><th>Result</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.normalized.name||'Unmatched product'}<small>{row.normalized.sku||row.normalized.barcode||'No identifier'}</small></td><td>{row.normalized.batchNumber||'No batch'}<small>{row.normalized.expiryDate||'No expiry'}</small></td><td>{row.normalized.quantity} {row.normalized.unit}</td><td>{row.normalized.baseQuantity}</td><td>{money(row.normalized.unitCostMinor)}</td><td>{row.errors.length?<ul>{row.errors.map(message=><li key={message}>{message}</li>)}</ul>:<span className="status-tag in-stock">READY</span>}</td></tr>)}</tbody></table></div><button className="primary" onClick={commit} disabled={busy||preview.errorRows>0||Boolean(status)}>Commit opening stock</button></section>}
 {status&&<p role="status" className="opening-success">{status}</p>}{error&&<p role="alert" className="error">{error}</p>}</div></Dialog>
}
