import {useEffect,useRef,useState} from 'react';
import {Dialog} from './shared';
type Unit={unitName:string;baseQuantity:string;price:string;isDefaultSaleUnit:boolean;allowsFractionalQuantity:boolean};
export function PackingEditor({id,onClose,onSaved}:{id:number;onClose:()=>void;onSaved:()=>void}){
 const [units,setUnits]=useState<Unit[]>([]),[name,setName]=useState(''),[base,setBase]=useState(''),[stamp,setStamp]=useState(''),[locked,setLocked]=useState(false),[oldNames,setOldNames]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[source,setSource]=useState(0);
 const saving=useRef(false);
 useEffect(()=>{let live=true;window.pharmacy.packingDetail({id}).then(r=>{if(!live)return;setName(String(r.product?.name));setBase(String(r.product?.baseUnit));setStamp(String(r.product?.updatedAt));setLocked(r.historyLocked);setOldNames((r.units||[]).map(u=>u.unit_name));setUnits((r.units||[]).map(u=>({unitName:u.unit_name,baseQuantity:String(u.base_quantity),price:String((u.selling_price_minor??Number(r.product?.defaultSalePriceMinor))/100),isDefaultSaleUnit:Boolean(u.is_default_sale_unit),allowsFractionalQuantity:Boolean(u.allows_fractional_quantity)})));}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[id]);
 const change=(i:number,patch:Partial<Unit>)=>setUnits(rows=>rows.map((u,j)=>j===i?{...u,...patch}:u));
 const derive=()=>{const s=units[source],ratio=Number(s?.baseQuantity),price=Number(s?.price);if(!s||!s.price||!Number.isFinite(ratio)||ratio<=0||!Number.isFinite(price)||price<0){setError('Enter a valid source unit quantity and price first.');return;}setError('');setUnits(rows=>rows.map(u=>({...u,price:String(Math.round(price*Number(u.baseQuantity)/ratio))})));};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setError('');try{await window.pharmacy.packingSave({id,updatedAt:stamp,units:units.map(u=>({...u,baseQuantity:Number(u.baseQuantity),sellingPriceMinor:Math.round(Number(u.price)*100)}))});onSaved();}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}};
 return <Dialog title={'Packing and prices'+(name?' — '+name:'')} onClose={()=>{if(!saving.current)onClose()}}><form onSubmit={save} className="packing-form"><p>Base unit: <strong>{base||'Loading…'}</strong>. Each quantity below is measured in this base unit. Example: 1 strip = 10 tablets, 1 box = 100 tablets.</p>{locked&&<p className="warning">This product has stock or history. Existing unit names and ratios are locked. New units and future selling prices can be configured without rebasing stock.</p>}<div className="packing-rows">{units.map((u,i)=>{const fixed=locked&&oldNames.includes(u.unitName);return <fieldset key={i} disabled={busy}><legend>Unit {i+1}</legend><label>Unit name<input aria-label={'Unit name '+(i+1)} required value={u.unitName} disabled={fixed||u.unitName===base} onChange={e=>change(i,{unitName:e.target.value})}/></label><label>Base quantity<input aria-label={'Base quantity '+(i+1)} required type="number" min="0.000001" step="any" disabled={fixed||u.unitName===base} value={u.baseQuantity} onChange={e=>change(i,{baseQuantity:e.target.value})}/></label><label>Price PKR<input aria-label={'Unit price '+(i+1)} required type="number" min="0" step="any" value={u.price} onChange={e=>change(i,{price:e.target.value})}/></label><label><input type="radio" name="default-unit" aria-label={'Default unit '+(i+1)} checked={u.isDefaultSaleUnit} onChange={()=>setUnits(rows=>rows.map((x,j)=>({...x,isDefaultSaleUnit:i===j})))}/>Default</label><label><input type="checkbox" aria-label={'Allow fractional '+(i+1)} checked={u.allowsFractionalQuantity} onChange={e=>change(i,{allowsFractionalQuantity:e.target.checked})}/>Fractional</label><button type="button" aria-label={'Remove unit '+(i+1)} disabled={fixed||u.unitName===base} onClick={()=>{setUnits(rows=>rows.filter((_,j)=>j!==i));setSource(0)}}>Remove</button></fieldset>})}</div><button type="button" disabled={busy||!stamp||units.length>=20} onClick={()=>setUnits(rows=>[...rows,{unitName:'',baseQuantity:'1',price:'0',isDefaultSaleUnit:false,allowsFractionalQuantity:false}])}>Add unit</button><div className="packing-calculate"><label>Calculate from<select aria-label="Price source unit" value={source} onChange={e=>setSource(Number(e.target.value))}>{units.map((u,i)=><option value={i} key={i}>{u.unitName||'Unit '+(i+1)}</option>)}</select></label><button type="button" disabled={busy||!units.length} onClick={derive}>Calculate other prices</button></div><p>Calculated and saved prices round to whole PKR. Calculating replaces the displayed prices; you can override them before saving. Recalculate explicitly after changing ratios or the source price. Sealed units and capsules cannot be sold fractionally.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" type="submit" disabled={busy||!stamp}>{busy?'Saving…':'Save packing'}</button></form></Dialog>;
}
