import {useState} from 'react';
import type {ProductImportInspection,ProductImportPreview} from './contracts';
import {Dialog} from './shared';
const FIELDS=[['sku','SKU'],['barcode','Barcode'],['name','Product name'],['generic_name','Generic name'],['manufacturer','Manufacturer'],['category','Category'],['product_type','Product type'],['dosage_form','Dosage form'],['strength','Strength'],['pack_description','Pack description'],['base_unit','Base unit'],['units_per_strip','Units per strip'],['strips_per_box','Strips per box'],['base_sale_price','Base sale price'],['strip_sale_price','Strip sale price'],['box_sale_price','Box sale price'],['minimum_stock','Minimum stock'],['reorder_level','Reorder level'],['prescription_required','Prescription required'],['controlled_medicine','Controlled medicine'],['gst_percent','GST percent'],['tax_status','Tax status'],['active','Active'],['notes','Notes']];
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('File could not be read'));reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.readAsDataURL(file)});
const download=(name:string,mime:string,base64:string)=>{const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:mime})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
export function ProductImport({onClose,onCommitted}:{onClose:()=>void;onCommitted:(message:string)=>void}){
 const [file,setFile]=useState<File|null>(null),[base64,setBase64]=useState(''),[inspection,setInspection]=useState<ProductImportInspection|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[policy,setPolicy]=useState('error'),[preview,setPreview]=useState<ProductImportPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const inspect=async()=>{if(!file)return;setBusy(true);setError('');setPreview(null);try{const encoded=await toBase64(file),result=await window.pharmacy.productImportInspect({name:file.name,base64:encoded});setBase64(encoded);setInspection(result);setMapping(result.suggestedMapping)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const runPreview=async()=>{if(!file||!inspection)return;setBusy(true);setError('');try{setPreview(await window.pharmacy.productImportPreview({name:file.name,base64,mapping,duplicatePolicy:policy}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const getTemplate=async()=>{setBusy(true);setError('');try{const r=await window.pharmacy.productImportTemplate();download(r.name,r.mime,r.base64)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const getErrors=async()=>{if(!preview)return;setBusy(true);try{const r=await window.pharmacy.productImportErrors({jobId:preview.jobId});download(r.name,r.mime,r.base64)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const commit=async()=>{if(!preview||preview.errorRows)return;setBusy(true);setError('');try{const r=await window.pharmacy.productImportCommit({jobId:preview.jobId});onCommitted(`${r.committedRows} product${r.committedRows===1?'':'s'} imported${r.skippedRows?` · ${r.skippedRows} skipped`:''}.`)}catch(e){setError((e as Error).message);setBusy(false)}};
 return <Dialog title="Import products" onClose={()=>{if(!busy)onClose()}}><div className="product-import"><section className="import-source"><button onClick={getTemplate} disabled={busy}>Download template</button><label>Product file<input aria-label="Product import file" type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setInspection(null);setPreview(null)}}/></label><button className="primary" onClick={inspect} disabled={busy||!file}>{busy?'Working…':'Read file'}</button><small>XLSX or CSV, maximum 5,000 product rows and 8 MB. Text barcodes retain leading zeroes.</small></section>{inspection&&<><section><h3>Map columns</h3><p>{inspection.totalRows} rows found. Confirm how source columns map to product fields.</p><div className="import-mapping">{FIELDS.map(([key,label])=><label key={key}>{label}{key==='name'&&' *'}<select aria-label={`Map ${label}`} value={mapping[key]||''} disabled={busy} onChange={e=>{setMapping(old=>({...old,[key]:e.target.value}));setPreview(null)}}><option value="">Not mapped</option>{inspection.headers.map(header=><option key={header} value={header}>{header} · {String(inspection.sampleRows[0]?.[header]??'').slice(0,35)}</option>)}</select></label>)}</div></section><section className="duplicate-policy"><label>When barcode or SKU already exists<select aria-label="Duplicate policy" value={policy} disabled={busy} onChange={e=>{setPolicy(e.target.value);setPreview(null)}}><option value="error">Stop with error</option><option value="skip">Skip existing product</option><option value="update">Update existing product</option></select></label>{policy==='update'&&<p className="warning">Update replaces product master values for matching barcode or SKU. Review the preview before committing.</p>}<button className="primary" disabled={busy||!mapping.name} onClick={runPreview}>Preview import</button></section></>}{preview&&<section className="import-preview"><h3>Preview result</h3><p role="status"><strong>{preview.validRows}</strong> ready · <strong>{preview.skippedRows}</strong> skipped · <strong>{preview.errorRows}</strong> errors</p><div><table><thead><tr><th>Row</th><th>Action</th><th>Product</th><th>Identifiers</th><th>Errors</th></tr></thead><tbody>{preview.rows.slice(0,200).map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td><strong>{row.action.toUpperCase()}</strong></td><td>{row.normalized.name||'—'}<small>{row.normalized.manufacturer||''}</small></td><td>{row.normalized.sku||'No SKU'}<small>{row.normalized.barcode||'No barcode'}</small></td><td>{row.errors.length?row.errors.join('; '):'—'}</td></tr>)}</tbody></table></div>{preview.errorRows>0?<button onClick={getErrors} disabled={busy}>Download error file</button>:<button className="primary" onClick={commit} disabled={busy}>{busy?'Committing…':'Commit product import'}</button>}</section>}{error&&<p className="error" role="alert">{error}</p>}</div></Dialog>
}
