import {useEffect,useRef,useState} from 'react';
import {Plus,Search,Pencil,Upload} from 'lucide-react';
import type {ProductSummary,ProductMasterResult} from './contracts';
import {Dialog,money} from './shared';
import {PackingEditor} from './Packing';
import {ProductImport} from './ProductImport';
type Fields=Record<string,string|boolean>;
const blank=():Fields=>({createKey:'TO-'+crypto.randomUUID(),name:'',barcode:'',genericName:'',manufacturer:'',category:'',productType:'medicine',dosageForm:'Tablet',strength:'',packDescription:'',baseUnit:'tablet',defaultSalePriceMinor:'0',boxSalePriceMinor:'',stripSalePriceMinor:'',minimumStock:'0',reorderLevel:'0',defaultSupplierId:'',prescriptionRequired:false,controlledMedicine:false,gstRateBasisPoints:'0',taxStatus:'exempt',active:true,notes:''});
export function Products(){
 const [q,setQ]=useState(''),[state,setState]=useState('active'),[page,setPage]=useState(1),[version,reload]=useState(0),[rows,setRows]=useState<ProductSummary[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState<Fields|null>(null),[suppliers,setSuppliers]=useState<{id:number;name:string}[]>([]),[busy,setBusy]=useState(false),[saveError,setSaveError]=useState(''),[confirm,setConfirm]=useState(false),[warning,setWarning]=useState(''),[saved,setSaved]=useState('');
 const [packingId,setPackingId]=useState<number|null>(null);
 const [importing,setImporting]=useState(false);
 const lock=useRef(false);
 useEffect(()=>{let live=true;setLoading(true);setError('');const t=setTimeout(()=>window.pharmacy.productList({q,state,page}).then(r=>{if(live){setRows(r.items);setTotal(r.total)}}).catch(e=>{if(live){setError(e.message);setRows([]);setTotal(0)}}).finally(()=>{if(live)setLoading(false)}),150);return()=>{live=false;clearTimeout(t)}},[q,state,page,version]);
 const open=async(id?:number)=>{setSaveError('');setWarning('');setConfirm(false);try{setSuppliers(await window.pharmacy.productSuppliers());if(id){const result=await window.pharmacy.productDetail({id});const value:Fields={};for(const[k,v]of Object.entries(result.product||{}))value[k]=typeof v==='boolean'?v:v==null?'':String(k.endsWith('PriceMinor')||k==='gstRateBasisPoints'?Number(v)/100:v);setEditor(value)}else setEditor(blank());}catch(e){setError((e as Error).message)}};
 const change=(key:string,value:string|boolean)=>{setEditor(old=>old?{...old,[key]:value}:old);setConfirm(false);setWarning('')};
 const field=(key:string,label:string,type='text',required=false)=><label key={key}>{label}<input aria-label={label} value={String(editor?.[key]??'')} type={type} required={required} min={type==='number'?'0':undefined} step={type==='number'?'any':undefined} maxLength={key==='notes'?2000:200} disabled={busy||(key==='baseUnit'&&Boolean(editor?.id))} onChange={e=>change(key,e.target.value)}/></label>;
 const select=(key:string,label:string,values:string[])=><label key={key}>{label}<select aria-label={label} value={String(editor?.[key]||'')} disabled={busy} onChange={e=>change(key,e.target.value)}>{values.map(v=><option key={v} value={v}>{v}</option>)}</select></label>;
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(lock.current||!editor)return;lock.current=true;setBusy(true);setSaveError('');const input:Record<string,unknown>={...editor,confirmDuplicateName:confirm};for(const k of ['defaultSalePriceMinor','boxSalePriceMinor','stripSalePriceMinor','gstRateBasisPoints'])input[k]=editor[k]===''?null:Math.round(Number(editor[k])*100);for(const k of ['minimumStock','reorderLevel'])input[k]=Number(editor[k]);input.defaultSupplierId=editor.defaultSupplierId?Number(editor.defaultSupplierId):null;if(editor.id)input.id=Number(editor.id);
 try{const r:ProductMasterResult=await window.pharmacy.productSave(input);if(r.needsConfirmation){setWarning('An active product has the same name. Check manufacturer and strength before confirming a separate product.');return;}setSaved('Product saved: '+r.product?.name);setEditor(null);reload(v=>v+1);}catch(e){setSaveError((e as Error).message)}finally{lock.current=false;setBusy(false)}};
 return <section className="products-page"><h1>Products</h1><p>Product identity and prices. Opening stock and purchase costs belong to batch receipt workflows.</p><div className="master-toolbar"><label><Search size={17}/><input aria-label="Search products" placeholder="Name, generic, barcode or product ID" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><select aria-label="Product status filter" value={state} onChange={e=>{setState(e.target.value);setPage(1)}}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All products</option></select><button onClick={()=>setImporting(true)}><Upload size={17}/> Import products</button><button className="primary" onClick={()=>open()}><Plus size={17}/> Add product</button></div>{error&&<p className="error" role="alert">{error}</p>}{saved&&<p role="status">{saved}</p>}<div className="panel master-table"><table><thead><tr><th>Product</th><th>Barcode</th><th>Manufacturer / strength</th><th>Base unit</th><th>Base price (PKR)</th><th>Status</th><th>Action</th></tr></thead><tbody>{!loading&&rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.generic_name||'—'}</small><small>#{p.id}</small></td><td>{p.barcode||'No barcode'}</td><td>{[p.manufacturer,p.strength].filter(Boolean).join(' · ')||'—'}</td><td>{p.base_unit}</td><td>{money(p.default_sale_price_minor)}</td><td>{p.active?'Active':'Inactive'}</td><td><button aria-label={'Edit '+p.name} onClick={()=>open(p.id)}><Pencil size={15}/> Edit</button><button aria-label={'Packing '+p.name} onClick={()=>setPackingId(p.id)}>Packing</button></td></tr>)}</tbody></table>{loading?<p role="status">Loading products…</p>:!rows.length&&<p>No products found.</p>}</div><div className="master-pagination"><button disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{total} products · Page {page} of {Math.max(1,Math.ceil(total/25))}</span><button disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div>
 {importing&&<ProductImport onClose={()=>setImporting(false)} onCommitted={message=>{setImporting(false);setSaved(message);reload(v=>v+1)}}/>}
 {packingId!==null&&<PackingEditor id={packingId} onClose={()=>setPackingId(null)} onSaved={()=>{setPackingId(null);reload(v=>v+1)}}/>}
 {editor&&<Dialog title={editor.id?'Edit product':'Add product'} onClose={()=>{if(!lock.current)setEditor(null)}}><form className="product-form" onSubmit={save}><p>{editor.id?'Product #'+editor.id+' · Base unit locked to protect existing stock.':'Permanent product ID is generated automatically.'}</p><div className="product-fields">{field('name','Product name','text',true)}{field('barcode','Barcode')}{field('genericName','Generic name')}{field('manufacturer','Manufacturer')}{field('category','Category')}{select('productType','Product type',['medicine','general','cosmetic','device','other'])}{select('dosageForm','Dosage form',['Tablet','Capsule','Syrup','Injection','Cream','Drops','Sachet','Ointment','Suspension','Inhaler','Device','Other'])}{field('strength','Strength')}{field('packDescription','Pack description')}{field('baseUnit','Base unit','text',true)}{field('defaultSalePriceMinor','Base selling price PKR','number',true)}{field('boxSalePriceMinor','Box selling price PKR','number')}{field('stripSalePriceMinor','Strip selling price PKR','number')}{field('minimumStock','Minimum stock (base units)','number',true)}{field('reorderLevel','Reorder level (base units)','number',true)}{select('taxStatus','Tax status',['exempt','taxable'])}{field('gstRateBasisPoints','GST percent','number',true)}<label>Default supplier<select aria-label="Default supplier" value={String(editor.defaultSupplierId)} disabled={busy} onChange={e=>change('defaultSupplierId',e.target.value)}><option value="">None</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{field('notes','Notes')}</div><div className="product-flags">{[['active','Active product'],['prescriptionRequired','Prescription required'],['controlledMedicine','Controlled medicine']].map(([k,l])=><label key={k}><input type="checkbox" checked={Boolean(editor[k])} disabled={busy} onChange={e=>change(k,e.target.checked)}/>{l}</label>)}</div><p>Deactivation hides the product from new sales and preserves its history. Pack conversions are configured separately.</p>{warning&&<div className="warning"><p>{warning}</p><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I confirm this is a separate product</label></div>}{saveError&&<p className="error" role="alert">{saveError}</p>}<button type="submit" className="primary" disabled={busy||Boolean(warning&&!confirm)}>{busy?'Saving…':'Save product'}</button></form></Dialog>}</section>
}
