import {useEffect,useMemo,useRef,useState} from 'react';
import {Plus,RefreshCw,Search,Eye,Truck,Building2,Trash2} from 'lucide-react';
import type {PurchaseDetail,PurchaseHistory,PurchaseInput,PurchasePreview,PurchaseProduct,Supplier,SupplierInput} from './contracts';
import {Dialog,dateLabel,money} from './shared';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Karachi'});
const key=()=>`TO-${crypto.randomUUID()}`;
type DraftLine={productId:number;purchaseUnit:string;purchasedQuantity:string;bonusQuantity:string;unitCost:string;salePrice:string;batchNumber:string;expiryDate:string;manufacturingDate:string;updateSellingPrice:boolean};
const blankLine=():DraftLine=>({productId:0,purchaseUnit:'',purchasedQuantity:'1',bonusQuantity:'0',unitCost:'0',salePrice:'0',batchNumber:'',expiryDate:'',manufacturingDate:'',updateSellingPrice:false});
const emptySupplier=():SupplierInput=>({name:'',phone:'',email:'',address:'',active:true});

export function Purchases({initialTab='purchases'}:{initialTab?:'purchases'|'suppliers'}){
 const [tab,setTab]=useState<'purchases'|'suppliers'|'history'>(initialTab),[suppliers,setSuppliers]=useState<Supplier[]>([]),[products,setProducts]=useState<PurchaseProduct[]>([]),[history,setHistory]=useState<PurchaseHistory[]>([]);
 const [supplierSearch,setSupplierSearch]=useState(''),[productSearch,setProductSearch]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 const [supplierEditor,setSupplierEditor]=useState<SupplierInput|null>(null),[detail,setDetail]=useState<PurchaseDetail|null>(null),[preview,setPreview]=useState<PurchasePreview|null>(null);
 const reference=useRef(key());
 const [supplierId,setSupplierId]=useState(0),[invoice,setInvoice]=useState(''),[purchasedAt,setPurchasedAt]=useState(today()),[method,setMethod]=useState('cash'),[paid,setPaid]=useState(''),[dueDate,setDueDate]=useState(''),[notes,setNotes]=useState(''),[lines,setLines]=useState<DraftLine[]>([blankLine()]);
 const load=async()=>{setLoading(true);setError('');try{const [s,p,h]=await Promise.all([window.pharmacy.supplierList({q:supplierSearch}),window.pharmacy.purchaseProducts({q:productSearch}),window.pharmacy.purchaseHistory({})]);setSuppliers(s);setProducts(p);setHistory(h);if(!supplierId&&s[0])setSupplierId(s[0].id)}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{const timer=setTimeout(load,120);return()=>clearTimeout(timer)},[supplierSearch,productSearch]);
 const payload=():PurchaseInput=>({supplierId,invoiceNumber:invoice,purchasedAt:purchasedAt+'T12:00:00.000+05:00',paymentMethod:method,amountPaidMinor:Math.round((paid===''?(method==='credit'?0:total):Number(paid))*100),dueDate,notes,idempotencyKey:reference.current,items:lines.map(x=>({productId:x.productId,purchaseUnit:x.purchaseUnit,purchasedQuantity:Number(x.purchasedQuantity),bonusQuantity:Number(x.bonusQuantity),unitCostMinor:Math.round(Number(x.unitCost)*100),salePriceMinor:Math.round(Number(x.salePrice)*100),batchNumber:x.batchNumber,expiryDate:x.expiryDate,manufacturingDate:x.manufacturingDate,updateSellingPrice:x.updateSellingPrice}))});
 const changeLine=(index:number,patch:Partial<DraftLine>)=>{setPreview(null);setLines(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row))};
 const selectProduct=(index:number,id:number)=>{const product=products.find(x=>x.id===id),unit=product?.units.find(x=>x.default)||product?.units[0];changeLine(index,{productId:id,purchaseUnit:unit?.unitName||'',salePrice:String((unit?.sellingPriceMinor??product?.default_sale_price_minor??0)/100)})};
 const total=useMemo(()=>lines.reduce((sum,x)=>sum+Number(x.purchasedQuantity||0)*Number(x.unitCost||0),0),[lines]);
 const saveSupplier=async(event:React.FormEvent)=>{event.preventDefault();if(!supplierEditor)return;setLoading(true);setError('');try{const saved=await window.pharmacy.supplierSave(supplierEditor);setSupplierEditor(null);setStatus(`Supplier ${saved.name} saved.`);await load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const inspect=async()=>{setError('');setStatus('');try{setPreview(await window.pharmacy.purchasePreview(payload()))}catch(e){setError((e as Error).message)}};
 const post=async()=>{if(!preview)return;setLoading(true);setError('');try{const result=await window.pharmacy.purchasePost(payload());setStatus(`Purchase #${result.purchaseId} posted. Paid ${money(result.amountPaidMinor)} · Due ${money(result.balanceDueMinor)}.`);setPreview(null);reference.current=key();setInvoice('');setPaid('');setDueDate('');setNotes('');setLines([blankLine()]);await load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 return <section className="purchases-page"><div className="page-title"><div><h1>{initialTab==='suppliers'?'Suppliers':'Purchases'}</h1><p>Receive supplier invoices with batch, units, bonus stock, effective cost and payable control.</p></div><button onClick={()=>load()} disabled={loading}><RefreshCw size={16}/> Refresh</button></div>
  <div className="segmented purchase-tabs"><button aria-pressed={tab==='purchases'} onClick={()=>setTab('purchases')}><Truck size={16}/> Receiving</button><button aria-pressed={tab==='suppliers'} onClick={()=>setTab('suppliers')}><Building2 size={16}/> Suppliers</button><button aria-pressed={tab==='history'} onClick={()=>setTab('history')}>Purchase history</button></div>
  {error&&<p className="error" role="alert">{error}</p>}{status&&<p role="status">{status}</p>}
  {tab==='suppliers'?<><div className="inventory-toolbar"><label><Search size={17}/><input aria-label="Search suppliers" placeholder="Supplier name or phone" value={supplierSearch} onChange={e=>setSupplierSearch(e.target.value)}/></label><button className="primary" onClick={()=>setSupplierEditor(emptySupplier())}><Plus size={16}/> Add supplier</button></div><div className="panel inventory-table"><table><thead><tr><th>Supplier</th><th>Contact</th><th>Purchases</th><th>Outstanding</th><th>Status</th><th>Action</th></tr></thead><tbody>{suppliers.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.address||'No address'}</small></td><td>{s.phone||'—'}<small>{s.email||'No email'}</small></td><td>{s.purchase_count||0}</td><td>{money(s.balance_minor||0)}</td><td>{s.active?'Active':'Inactive'}</td><td><button onClick={()=>setSupplierEditor({id:s.id,name:s.name,phone:s.phone||'',email:s.email||'',address:s.address||'',active:Boolean(s.active)})}>Edit</button></td></tr>)}</tbody></table>{!suppliers.length&&<p>No suppliers match.</p>}</div></>:
  null}
  {tab==='history'&&<div className="panel inventory-table"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Date</th><th>Lines</th><th>Total</th><th>Paid</th><th>Due</th><th>Action</th></tr></thead><tbody>{history.map(row=><tr key={row.id}><td>{row.invoice_number||'#'+row.id}</td><td>{row.supplier_name}</td><td>{dateLabel(row.purchased_at)}</td><td>{row.item_count}</td><td>{money(row.total_minor)}</td><td>{money(row.amount_paid_minor)}</td><td>{money(row.balance_due_minor)}</td><td><button onClick={async()=>setDetail(await window.pharmacy.purchaseDetail({id:row.id}))}><Eye size={15}/> View</button></td></tr>)}</tbody></table>{!history.length&&<p>No purchases posted yet.</p>}</div>}
  {tab==='purchases'&&<div className="purchase-layout"><div className="panel purchase-entry"><div className="purchase-fields"><label>Supplier<select aria-label="Purchase supplier" value={supplierId} onChange={e=>{setSupplierId(Number(e.target.value));setPreview(null)}}><option value="">Select supplier</option>{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Invoice number<input aria-label="Purchase invoice number" value={invoice} maxLength={100} onChange={e=>{setInvoice(e.target.value);setPreview(null)}}/></label><label>Purchase date<input aria-label="Purchase date" type="date" value={purchasedAt} onChange={e=>{setPurchasedAt(e.target.value);setPreview(null)}}/></label><label>Payment method<select aria-label="Purchase payment method" value={method} onChange={e=>{setMethod(e.target.value);setPreview(null)}}><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="mobile_wallet">Mobile wallet</option><option value="other">Other</option><option value="credit">Credit</option></select></label><label>Amount paid (PKR)<input aria-label="Purchase amount paid" type="number" min="0" step="0.01" value={paid} onChange={e=>{setPaid(e.target.value);setPreview(null)}}/></label><label>Due date<input aria-label="Purchase due date" type="date" min={purchasedAt} value={dueDate} onChange={e=>{setDueDate(e.target.value);setPreview(null)}}/></label><label className="wide">Notes<input aria-label="Purchase notes" maxLength={500} value={notes} onChange={e=>{setNotes(e.target.value);setPreview(null)}}/></label></div>
   <div className="purchase-product-search"><Search size={16}/><input aria-label="Search purchase products" placeholder="Search product for line selection" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/></div>
   <div className="purchase-lines">{lines.map((line,index)=>{const product=products.find(x=>x.id===line.productId);return <fieldset key={index}><legend>Line {index+1}</legend><label>Product<select aria-label={`Purchase product ${index+1}`} value={line.productId} onChange={e=>selectProduct(index,Number(e.target.value))}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{p.generic_name?' · '+p.generic_name:''}</option>)}</select></label><label>Unit<select aria-label={`Purchase unit ${index+1}`} value={line.purchaseUnit} onChange={e=>changeLine(index,{purchaseUnit:e.target.value})}>{product?.units.map(u=><option key={u.unitName}>{u.unitName}</option>)}</select></label><label>Purchased<input aria-label={`Purchased quantity ${index+1}`} type="number" min="0" step="any" value={line.purchasedQuantity} onChange={e=>changeLine(index,{purchasedQuantity:e.target.value})}/></label><label>Bonus<input aria-label={`Bonus quantity ${index+1}`} type="number" min="0" step="any" value={line.bonusQuantity} onChange={e=>changeLine(index,{bonusQuantity:e.target.value})}/></label><label>Unit cost PKR<input aria-label={`Unit cost ${index+1}`} type="number" min="0" step="0.01" value={line.unitCost} onChange={e=>changeLine(index,{unitCost:e.target.value})}/></label><label>Selling price PKR<input aria-label={`Selling price ${index+1}`} type="number" min="0" step="0.01" value={line.salePrice} onChange={e=>changeLine(index,{salePrice:e.target.value})}/></label><label>Batch<input aria-label={`Batch number ${index+1}`} required={product?.product_type==='medicine'} value={line.batchNumber} onChange={e=>changeLine(index,{batchNumber:e.target.value})}/></label><label>Expiry<input aria-label={`Expiry ${index+1}`} placeholder="YYYY-MM-DD or MM/YYYY" required={product?.product_type==='medicine'} value={line.expiryDate} onChange={e=>changeLine(index,{expiryDate:e.target.value})}/></label><label>Manufactured<input aria-label={`Manufacturing date ${index+1}`} placeholder="YYYY-MM-DD or MM/YYYY" value={line.manufacturingDate} onChange={e=>changeLine(index,{manufacturingDate:e.target.value})}/></label><label className="purchase-check"><input aria-label={`Update selling price ${index+1}`} type="checkbox" checked={line.updateSellingPrice} onChange={e=>changeLine(index,{updateSellingPrice:e.target.checked})}/> Update this unit's future selling price</label><button aria-label={`Remove purchase line ${index+1}`} disabled={lines.length===1} onClick={()=>{setLines(rows=>rows.filter((_,i)=>i!==index));setPreview(null)}}><Trash2 size={15}/> Remove</button></fieldset>})}</div><div className="purchase-actions"><button onClick={()=>{setLines(rows=>[...rows,blankLine()]);setPreview(null)}}><Plus size={15}/> Add line</button><span>Draft total <strong>PKR {total.toLocaleString('en-PK',{minimumFractionDigits:2})}</strong></span><button className="primary" onClick={inspect} disabled={loading}>Review purchase</button></div></div>
   <aside className="panel purchase-history"><h2>Purchase history</h2>{history.map(row=><button key={row.id} onClick={async()=>{try{setDetail(await window.pharmacy.purchaseDetail({id:row.id}))}catch(e){setError((e as Error).message)}}}><span><strong>{row.invoice_number||'#'+row.id}</strong><small>{row.supplier_name} · {dateLabel(row.purchased_at)}</small></span><span>{money(row.total_minor)}<small>{row.balance_due_minor?money(row.balance_due_minor)+' due':'Paid'}</small></span><Eye size={15}/></button>)}{!history.length&&<p>No purchases posted yet.</p>}</aside></div>}
  {supplierEditor&&<Dialog title={supplierEditor.id?'Edit supplier':'Add supplier'} onClose={()=>setSupplierEditor(null)}><form className="supplier-form" onSubmit={saveSupplier}><label>Name<input aria-label="Supplier name" required maxLength={200} value={supplierEditor.name} onChange={e=>setSupplierEditor({...supplierEditor,name:e.target.value})}/></label><label>Phone<input aria-label="Supplier phone" maxLength={50} value={supplierEditor.phone} onChange={e=>setSupplierEditor({...supplierEditor,phone:e.target.value})}/></label><label>Email<input aria-label="Supplier email" type="email" maxLength={200} value={supplierEditor.email} onChange={e=>setSupplierEditor({...supplierEditor,email:e.target.value})}/></label><label>Address<textarea aria-label="Supplier address" maxLength={500} value={supplierEditor.address} onChange={e=>setSupplierEditor({...supplierEditor,address:e.target.value})}/></label><label><input aria-label="Supplier active" type="checkbox" checked={supplierEditor.active} onChange={e=>setSupplierEditor({...supplierEditor,active:e.target.checked})}/> Active supplier</label><button className="primary" disabled={loading}>Save supplier</button></form></Dialog>}
  {preview&&<Dialog title="Review purchase" onClose={()=>!loading&&setPreview(null)}><div className="purchase-review"><p>Invoice <strong>{preview.invoiceNumber}</strong> · {preview.lines.length} line(s)</p>{preview.lines.map(x=><article key={x.line}><div><strong>{x.name}</strong><small>{x.purchasedQuantity} + {x.bonusQuantity} bonus {x.purchaseUnit} · {x.baseQuantityReceived} base units · Batch {x.batchNumber||'n.a.'}</small></div><span>{money(x.lineTotalMinor)}<small>{money(x.effectiveUnitCostMinor)} / base unit</small></span></article>)}<dl><div><dt>Total</dt><dd>{money(preview.totalMinor)}</dd></div><div><dt>Paid</dt><dd>{money(preview.amountPaidMinor)}</dd></div><div><dt>Due</dt><dd>{money(preview.balanceDueMinor)}</dd></div></dl><p className="warning">Posting creates stock, purchase cost, actual payment, supplier payable and audit records together. Posted history is not edited.</p><button className="primary" onClick={post} disabled={loading}>{loading?'Posting…':'Post purchase'}</button></div></Dialog>}
  {detail&&<Dialog title={'Purchase '+(detail.invoice_number||'#'+detail.id)} onClose={()=>setDetail(null)}><div className="purchase-review"><p><strong>{detail.supplier_name}</strong> · {dateLabel(detail.purchased_at)}</p>{detail.items.map(item=><article key={item.id}><div><strong>{item.product_name}</strong><small>{item.purchased_quantity} + {item.bonus_quantity} bonus {item.purchase_unit} · Batch {item.batch_number||'n.a.'} · Expiry {item.expiry_date||'n.a.'}</small></div><span>{money(item.line_total_minor)}<small>{money(item.effective_unit_cost_minor)} / base unit</small></span></article>)}<dl><div><dt>Total</dt><dd>{money(detail.total_minor)}</dd></div><div><dt>Paid</dt><dd>{money(detail.amount_paid_minor)}</dd></div><div><dt>Due</dt><dd>{money(detail.balance_due_minor)}</dd></div></dl></div></Dialog>}
 </section>
}
