import {useEffect,useState} from 'react';
import {Search,Eye,Printer,RotateCcw,UserRoundSearch,WalletCards,RefreshCw,ArrowLeft} from 'lucide-react';
import type {InvoiceDetail,InvoiceSearchInput,InvoiceSearchResult,Receipt} from './contracts';
import {Dialog,dateLabel,money} from './shared';

const blank=():InvoiceSearchInput=>({invoiceNumber:'',product:'',phone:'',paymentStatus:'',dateFrom:'',dateTo:'',page:1});

function ReceiptCopy({receipt,label}:{receipt:Receipt;label:string}){
 const totalDiscount=receipt.totals.lineDiscountMinor+receipt.totals.invoiceDiscountMinor;
 return <article className="historical-receipt" aria-label={label}>
  <header className="receipt-brand"><h2>{receipt.profile.pharmacyName}</h2>{receipt.profile.address&&<p>{receipt.profile.address}</p>}{receipt.profile.phone&&<p>Phone: {receipt.profile.phone}</p>}{receipt.profile.taxRegistration&&<p>Tax/NTN: {receipt.profile.taxRegistration}</p>}<strong>{label}</strong></header>
  <dl className="receipt-meta"><div><dt>Invoice</dt><dd>{receipt.invoiceNumber}</dd></div><div><dt>Date</dt><dd>{dateLabel(receipt.soldAt)}</dd></div><div><dt>Cashier</dt><dd>{receipt.cashier.name}</dd></div><div><dt>Customer</dt><dd>{receipt.customer.name||'Walk-in'}{receipt.customer.phone?` · ${receipt.customer.phone}`:''}</dd></div></dl>
  <div className="receipt-items">{receipt.items.map(item=><section key={item.lineNumber}><div className="receipt-product"><strong>{item.productName}</strong>{item.genericName&&<small>{item.genericName}</small>}</div><div><span>{item.quantity} {item.saleUnit} × {money(item.unitPriceMinor)}</span><strong>{money(item.lineTotalMinor)}</strong></div>{item.lineDiscountMinor>0&&<small>Line discount: {money(item.lineDiscountMinor)}</small>}{item.invoiceDiscountMinor>0&&<small>Invoice discount share: {money(item.invoiceDiscountMinor)}</small>}{item.gstMinor>0&&<small>GST {item.gstRateBasisPoints/100}%: {money(item.gstMinor)}</small>}</section>)}</div>
  <dl className="receipt-totals"><div><dt>Gross</dt><dd>{money(receipt.totals.grossMinor)}</dd></div>{totalDiscount>0&&<div><dt>Discounts</dt><dd>-{money(totalDiscount)}</dd></div>}<div><dt>GST</dt><dd>{money(receipt.totals.gstMinor)}</dd></div>{receipt.totals.roundingMinor!==0&&<div><dt>Rounding</dt><dd>{money(receipt.totals.roundingMinor)}</dd></div>}<div className="receipt-grand"><dt>Total PKR</dt><dd>{money(receipt.totals.finalTotalMinor)}</dd></div><div><dt>Paid</dt><dd>{money(receipt.payment.amountPaidMinor)}</dd></div>{receipt.payment.cashTenderedMinor!=null&&<div><dt>Cash tendered</dt><dd>{money(receipt.payment.cashTenderedMinor)}</dd></div>}{receipt.payment.cashChangeMinor!=null&&<div><dt>Change</dt><dd>{money(receipt.payment.cashChangeMinor)}</dd></div>}<div><dt>Due</dt><dd>{money(receipt.payment.balanceDueMinor)}</dd></div>{receipt.payment.dueDate&&<div><dt>Due date</dt><dd>{receipt.payment.dueDate}</dd></div>}<div><dt>Payment</dt><dd>{receipt.payment.method}</dd></div></dl>
  <footer><p>{receipt.profile.footer}</p><small>Historical reprint · saved invoice snapshot</small></footer>
 </article>;
}

function HistoricalReceipt({detail,onBack}:{detail:InvoiceDetail;onBack:()=>void}){
 return <div className="historical-receipt-shell"><div className="receipt-preview-actions"><button onClick={onBack}><ArrowLeft size={15}/> Back to invoice</button><button className="primary" onClick={()=>window.print()}><Printer size={15}/> Print both copies</button></div><div className="historical-receipt-print"><ReceiptCopy receipt={detail.receipt} label="Customer copy"/><ReceiptCopy receipt={detail.receipt} label="Pharmacy copy"/></div></div>;
}

export function SalesHistory(){
 const [filters,setFilters]=useState<InvoiceSearchInput>(blank()),[result,setResult]=useState<InvoiceSearchResult>({items:[],total:0,page:1,pageSize:25}),[detail,setDetail]=useState<InvoiceDetail|null>(null),[history,setHistory]=useState<InvoiceSearchResult|null>(null),[returnStart,setReturnStart]=useState(false),[showDue,setShowDue]=useState(false),[receiptOpen,setReceiptOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=async(next=filters)=>{setLoading(true);setError('');try{setResult(await window.pharmacy.invoiceSearch(next));setFilters(next)}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{void load(blank())},[]);
 const change=(key:keyof InvoiceSearchInput,value:string)=>setFilters(old=>({...old,[key]:value,page:1}));
 const open=async(id:number)=>{setLoading(true);setError('');try{setDetail(await window.pharmacy.invoiceDetail({id}));setHistory(null);setReturnStart(false);setShowDue(false);setReceiptOpen(false)}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 return <section className="sales-history-page"><div className="page-title"><div><h1>Sales History</h1><p>Search saved invoices, review customer history and open authorized follow-up actions.</p></div><button onClick={()=>load(filters)} disabled={loading}><RefreshCw size={16}/> Refresh</button></div>
 {error&&<p className="error" role="alert">{error}</p>}
 <form className="panel invoice-filters" onSubmit={e=>{e.preventDefault();void load({...filters,page:1})}}><label>Invoice<input aria-label="Invoice number filter" value={filters.invoiceNumber} onChange={e=>change('invoiceNumber',e.target.value)}/></label><label>Medicine<input aria-label="Medicine filter" value={filters.product} onChange={e=>change('product',e.target.value)}/></label><label>Customer phone<input aria-label="Customer phone filter" value={filters.phone} onChange={e=>change('phone',e.target.value)}/></label><label>Status<select aria-label="Payment status filter" value={filters.paymentStatus} onChange={e=>change('paymentStatus',e.target.value)}><option value="">All statuses</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="credit">Credit</option><option value="reversed">Reversed</option></select></label><label>From<input aria-label="Sale date from" type="date" value={filters.dateFrom} onChange={e=>change('dateFrom',e.target.value)}/></label><label>To<input aria-label="Sale date to" type="date" value={filters.dateTo} onChange={e=>change('dateTo',e.target.value)}/></label><button className="primary" disabled={loading}><Search size={16}/> Search</button><button type="button" onClick={()=>{const next=blank();setFilters(next);void load(next)}}>Clear</button></form>
 <div className="panel inventory-table"><table><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Medicines</th><th>Payment</th><th>Total</th><th>Due</th><th>Action</th></tr></thead><tbody>{result.items.map(row=><tr key={row.id}><td><strong>{row.invoice_number}</strong></td><td>{dateLabel(row.sold_at)}</td><td>{row.customer_name_snapshot||'Walk-in'}<small>{row.customer_phone_snapshot||'No phone'}</small></td><td>{row.products||'—'}</td><td><span className={`status-tag ${row.payment_status}`}>{row.payment_status}</span><small>{row.payment_method}</small></td><td>{money(row.final_total_minor)}</td><td>{money(row.balance_due_minor)}<small>{row.due_date||''}</small></td><td><button onClick={()=>void open(row.id)}><Eye size={15}/> View</button></td></tr>)}</tbody></table>{!result.items.length&&<p>No invoices match these filters.</p>}</div>
 <div className="pager"><button disabled={result.page<=1||loading} onClick={()=>load({...filters,page:result.page-1})}>Previous</button><span>Page {result.page} · {result.total} invoices</span><button disabled={result.page*result.pageSize>=result.total||loading} onClick={()=>load({...filters,page:result.page+1})}>Next</button></div>
 {detail&&<Dialog title={receiptOpen?`Receipt ${detail.invoiceNumber}`:`Invoice ${detail.invoiceNumber}`} onClose={()=>setDetail(null)}>{receiptOpen?<HistoricalReceipt detail={detail} onBack={()=>setReceiptOpen(false)}/>:<div className="invoice-detail"><div className="invoice-detail-head"><div><strong>{dateLabel(detail.soldAt)}</strong><small>{detail.customer.name||'Walk-in customer'} · {detail.customer.phone||'No phone'}</small></div><div><strong>{money(detail.totals.finalTotalMinor)}</strong><small>{detail.payment.status} · {detail.payment.method}</small></div></div><table><thead><tr><th>Medicine</th><th>Qty</th><th>Rate</th><th>Discount</th><th>GST</th><th>Total</th><th>Returned</th></tr></thead><tbody>{detail.items.map(item=><tr key={item.id}><td>{item.productName}<small>{item.genericName||''}</small></td><td>{item.quantity} {item.saleUnit}</td><td>{money(item.unitPriceMinor)}</td><td>{money(item.lineDiscountMinor)}</td><td>{money(item.gstMinor)}</td><td>{money(item.lineTotalMinor)}</td><td>{item.returnedBaseQuantity} / {item.baseQuantity}</td></tr>)}</tbody></table><div className="invoice-action-row">{detail.actions.canPrint&&<button onClick={()=>setReceiptOpen(true)}><Printer size={15}/> Reprint saved receipt</button>}{detail.actions.canViewCustomerHistory&&<button onClick={async()=>{setHistory(await window.pharmacy.customerHistory({phone:detail.customer.phone||''}));setReturnStart(false)}}><UserRoundSearch size={15}/> Customer history</button>}{detail.receivable&&<button onClick={()=>{setShowDue(true);setReturnStart(false)}}><WalletCards size={15}/> Open due</button>}{detail.actions.canStartReturn&&<button onClick={()=>{setReturnStart(true);setShowDue(false)}}><RotateCcw size={15}/> Start return</button>}</div>
 {showDue&&detail.receivable&&<section className="invoice-followup" aria-label="Invoice due"><h3>Outstanding due</h3><p>{money(detail.receivable.balance_minor)} · Due {detail.receivable.due_date} · {detail.receivable.status}</p>{detail.payments.map(payment=><small key={payment.id}>{dateLabel(payment.collected_at)} · {money(payment.amount_minor)} · {payment.method}</small>)}</section>}
 {returnStart&&<section className="invoice-followup" aria-label="Return start"><h3>Return start</h3><p>Original saved quantities are shown below. Final return posting remains protected by the dedicated customer-return workflow.</p>{detail.items.map(item=><div key={item.id}><span>{item.productName}</span><strong>{item.returnableBaseQuantity} base units returnable</strong></div>)}</section>}
 {history&&<section className="invoice-followup" aria-label="Customer history"><h3>Customer history</h3>{history.items.map(row=><button key={row.id} onClick={()=>void open(row.id)}><span>{row.invoice_number} · {dateLabel(row.sold_at)} · {row.products}</span><strong>{money(row.final_total_minor)} · {money(row.balance_due_minor)} due</strong></button>)}</section>}
 {detail.actions.canViewAudit&&<details className="invoice-audit"><summary>Authorized audit view ({detail.audit.length})</summary>{detail.audit.map(row=><p key={row.id}><strong>{row.action}</strong> · {dateLabel(row.occurred_at)}{row.reason?` · ${row.reason}`:''}</p>)}</details>}</div>}</Dialog>}
 </section>;
}
