import {useEffect,useState} from 'react';
import type {SettlementReportInput,SettlementSummary,SettlementRow} from './contracts';
import {money,dateLabel} from './shared';
export function SettlementReport({vendorVisible}:{vendorVisible:boolean}){
 const initial:SettlementReportInput={range:'1m',type:'all',method:'all'};
 const [draft,setDraft]=useState(initial),[applied,setApplied]=useState(initial),[page,setPage]=useState(1);
 const [summary,setSummary]=useState<SettlementSummary|null>(null),[entries,setEntries]=useState<{hasMore:boolean;items:SettlementRow[]}|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setBusy(true);setError('');Promise.all([window.pharmacy.settlementSummary(applied),window.pharmacy.settlementEntries({...applied,page})]).then(([s,e])=>{if(active){setSummary(s);setEntries(e)}}).catch(e=>{if(active){setSummary(null);setEntries(null);setError((e as Error).message)}}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[applied,page]);
 return <>
  <div className="page-title"><h1>Due Payment/Collection Report</h1>{(['csv','xlsx','pdf'] as const).map(format=><button key={format} disabled={busy||!summary} onClick={async()=>{try{setError('');const r=await window.pharmacy.settlementExport({...applied,format});if(r.saved)setNotice(`${format.toUpperCase()} settlement report saved.`)}catch(e){setError((e as Error).message)}}}>Export {format.toUpperCase()}</button>)}</div>
  <section className="panel"><h2>Filters</h2><form onSubmit={e=>{e.preventDefault();setPage(1);setNotice('');setApplied({...draft})}}><div className="closing-form">
   <label>Payment dates<select aria-label="Payment dates" value={draft.range} onChange={e=>setDraft({...draft,range:e.target.value})}>{[['7d','7 Days'],['1m','1 Month'],['6m','6 Months'],['1y','1 Year'],['custom','Custom']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
   {draft.range==='custom'&&<><label>From<input type="date" value={draft.from||''} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>To<input type="date" value={draft.to||''} onChange={e=>setDraft({...draft,to:e.target.value})}/></label></>}
   <label>Payment account type<select aria-label="Payment account type" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as SettlementReportInput['type']})}><option value="all">All allowed accounts</option><option value="customer">Customer</option><option value="supplier">Supplier</option>{vendorVisible&&<option value="vendor">Vendor</option>}</select></label>
   <label>Settlement method<select aria-label="Settlement method" value={draft.method} onChange={e=>setDraft({...draft,method:e.target.value})}>{['all','cash','card','digital','bank_transfer','mobile_wallet','other'].map(x=><option key={x}>{x}</option>)}</select></label>
   {(['party','reference','actor'] as const).map(key=><label key={key}>{key==='party'?'Party name':key==='reference'?'Payment or invoice reference':'Recorded by'}<input maxLength={100} value={draft[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}
   </div><button className="primary">Run report</button></form><small>{summary?.scope}</small>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>
  <section className="panel"><h2>Settlement totals</h2>{summary&&<><p>{summary.range.from} to {summary.range.to} | Payments: {summary.totals.count}</p><p>Customer collections: PKR {money(summary.totals.inMinor)} | Supplier/vendor payments: PKR {money(summary.totals.outMinor)} | Net cash flow: PKR {money(summary.totals.netMinor)}</p>{summary.methods.map(x=><p key={x.method}>{x.method}: collected {money(x.inMinor)}, paid {money(x.outMinor)}</p>)}</>}</section>
  <section className="panel"><h2>Payment detail</h2>{entries?.items.length?<table><thead><tr><th>Date</th><th>Account</th><th>Party</th><th>Original invoice</th><th>Payment reference</th><th>Method</th><th>Direction</th><th>PKR</th><th>Recorded by</th></tr></thead><tbody>{entries.items.map(x=><tr key={`${x.type}:${x.id}`}><td>{dateLabel(x.occurredAt)}</td><td>{x.type}</td><td>{x.party}</td><td>{x.originReference}</td><td>{x.reference}</td><td>{x.method}</td><td>{x.direction}</td><td>{money(x.amountMinor)}</td><td>{x.actor}</td></tr>)}</tbody></table>:<p>No payments match these filters.</p>}<div className="segmented"><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={busy||!entries?.hasMore} onClick={()=>setPage(page+1)}>Next</button></div></section>
 </>;
}
