import {useEffect,useMemo,useState} from 'react';
import type {StockAdjustmentBatch} from './contracts';
import {Dialog} from './shared';
const quantityLabel=(value:number)=>Number(value).toLocaleString(undefined,{maximumFractionDigits:3});
const localNow=()=>{const date=new Date(),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)};
export function StockAdjustment({batchId,onClose,onCommitted}:{batchId:number;onClose:()=>void;onCommitted:(message:string)=>void}){
 const [batch,setBatch]=useState<StockAdjustmentBatch|null>(null),[mode,setMode]=useState('count'),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[occurredAt,setOccurredAt]=useState(localNow()),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;window.pharmacy.stockAdjustmentDetail({batchId}).then(data=>{if(live){setBatch(data);setQuantity(String(data.physicalQuantity))}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[batchId]);
 const number=Number(quantity),delta=useMemo(()=>!batch||!Number.isFinite(number)?null:mode==='count'?number-batch.physicalQuantity:-number,[batch,number,mode]);
 const valid=Boolean(batch&&reason.trim()&&delta&&Number.isFinite(delta)&&number>=0&&(mode==='count'||number>0)&&confirmed);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!valid)return;setBusy(true);setError('');try{const result=await window.pharmacy.stockAdjustmentPost({batchId,mode,quantity:number,reason:reason.trim(),occurredAt:new Date(occurredAt).toISOString(),idempotencyKey:'TO-ADJ-'+crypto.randomUUID()});onCommitted(`Stock adjustment #${result.adjustmentId} posted.`)}catch(e){setError((e as Error).message);setBusy(false)}};
 return <Dialog title="Adjust stock" onClose={()=>{if(!busy)onClose()}}><form className="stock-adjustment" onSubmit={submit}>{batch?<><div className="adjustment-batch"><div><h3>{batch.name}</h3><p>{batch.genericName||'No generic'} · Batch {batch.batchNumber||'#'+batch.batchId}</p></div><div><small>Current physical stock</small><strong>{quantityLabel(batch.physicalQuantity)} {batch.baseUnit}</strong></div></div>{batch.controlledMedicine&&<p className="warning">Controlled medicine: manager or administrator authorization is required and will be recorded.</p>}<div className="adjustment-fields"><label>Adjustment type<select aria-label="Adjustment type" value={mode} disabled={busy} onChange={e=>{setMode(e.target.value);setQuantity(e.target.value==='count'?String(batch.physicalQuantity):'');setConfirmed(false)}}><option value="count">Count correction</option><option value="loss">Damage / stock loss</option><option value="disposal">Expiry / disposal</option></select></label><label>{mode==='count'?'Counted physical quantity':'Quantity to remove'}<input aria-label={mode==='count'?'Counted physical quantity':'Quantity to remove'} type="number" min="0" step="any" required value={quantity} disabled={busy} onChange={e=>{setQuantity(e.target.value);setConfirmed(false)}}/></label><label>Occurred at<input aria-label="Adjustment occurred at" type="datetime-local" required value={occurredAt} disabled={busy} onChange={e=>{setOccurredAt(e.target.value);setConfirmed(false)}}/></label><label className="wide">Reason / notes<textarea aria-label="Adjustment reason" required maxLength={500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);setConfirmed(false)}} placeholder={mode==='count'?'Physical count reconciliation':mode==='loss'?'Damaged, missing or broken stock':'Expired or authorized disposal details'}/></label></div><div className="adjustment-preview"><span>Change <strong className={(delta||0)<0?'negative':''}>{delta&&delta>0?'+':''}{delta==null?'—':quantityLabel(delta)} {batch.baseUnit}</strong></span><span>Result <strong>{delta==null?'—':quantityLabel(batch.physicalQuantity+delta)} {batch.baseUnit}</strong></span></div>{delta===0&&<p className="warning">Counted quantity matches current stock; no adjustment is needed.</p>}{delta!==null&&batch.physicalQuantity+delta<0&&<p className="error" role="alert">This adjustment would make stock negative and cannot be posted.</p>}<label className="adjustment-confirm"><input aria-label="Confirm stock adjustment" type="checkbox" checked={confirmed} disabled={busy||!delta||batch.physicalQuantity+delta<0||!reason.trim()} onChange={e=>setConfirmed(e.target.checked)}/>I checked the batch, quantity, reason and resulting physical stock.</label><button className="primary" type="submit" disabled={busy||!valid}>{busy?'Posting…':'Post stock adjustment'}</button></>:<p role="status">Loading batch…</p>}{error&&<p className="error" role="alert">{error}</p>}</form></Dialog>
}
